/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Resepsionis;

import Database.KoneksiDatabase;
import Main.JFrame_Login;
import java.awt.CardLayout;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class JFrame_Main_Resepsionis extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Main_Resepsionis.class.getName());
    
    private final ImageIcon clinicIcon = new ImageIcon(getClass().getResource("/gambarKlinik.png"));
    
    // Atribut
    private String namaResepsionis = "Nama Default Resepsionis"; // Default value
    
    // Constructor Default
    public JFrame_Main_Resepsionis() {
        initComponents(); // Baris ini sudah ada, dibuat oleh NetBeans
        
        
//        // --- 1. SIAPKAN PANEL REGISTRASI (DENGAN SCROLL) ---
//        JPanel_Registrasi_Kunjungan panelReg = new JPanel_Registrasi_Kunjungan();
//
//        // Bungkus Panel Registrasi ke dalam JScrollPane
//        javax.swing.JScrollPane scrollReg = new javax.swing.JScrollPane(panelReg);
//        scrollReg.setBorder(null); // Hilangkan border biar rapi
//        scrollReg.getVerticalScrollBar().setUnitIncrement(20); // Scroll biar cepat

        
        
        // Memusatkan jendela (ini mungkin sudah Anda tambahkan)
        this.setLocationRelativeTo(null); 

        // --- TAMBAHKAN BARIS INI UNTUK MEMBUAT FULLSCREEN ---
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Menjadwalkan update gambar setelah ukuran tombol tersedia
        SwingUtilities.invokeLater(() -> {
            // Sesuaikan ukuran gambar
            labelIconKlinik.setIcon(new ImageIcon(clinicIcon.getImage().getScaledInstance(labelIconKlinik.getWidth(), labelIconKlinik.getHeight(), Image.SCALE_SMOOTH)));
        });
        
        // 1. Inisialisasi semua panel halaman
        JPanel_Dashboard_Resepsionis panelDashboard = new JPanel_Dashboard_Resepsionis(this.namaResepsionis);
        JPanel_Manajemen_Pasien panelPasien = new JPanel_Manajemen_Pasien();
        JPanel_Informasi_Dokter panelDokter = new JPanel_Informasi_Dokter();
        JPanel_Manajemen_Jadwal panelJadwal = new JPanel_Manajemen_Jadwal();
        JPanel_Registrasi_Kunjungan panelRegistrasiKunjungan = new JPanel_Registrasi_Kunjungan();

        // 2. Tambahkan panel-panel tersebut ke panelContent
        // "cardDashboard" adalah nama unik (key) untuk memanggil panel itu
        panelContent.add(panelDashboard, "cardDashboard");
        panelContent.add(panelPasien, "cardPasien");
        panelContent.add(panelDokter, "cardDokter");
        panelContent.add(panelJadwal, "cardJadwal");
        panelContent.add(panelRegistrasiKunjungan, "cardRegistrasiKunjungan");

        // 3. Tampilkan panel pertama (dashboard) saat aplikasi dibuka
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardDashboard");
        
//        java.awt.CardLayout cl = (java.awt.CardLayout) panelContent.getLayout();
//        cl.show(panelContent, "cardDashboard");
    }
    
    // Constructor Login
    public JFrame_Main_Resepsionis(int userId, String paramNamaResepsionis) {
        this();
        
        this.namaResepsionis = paramNamaResepsionis;
        
        // Cara Paling Aman (Re-add Dashboard):
        JPanel_Dashboard_Resepsionis panelDashboardBaru = new JPanel_Dashboard_Resepsionis(paramNamaResepsionis);
        panelContent.add(panelDashboardBaru, "cardDashboard");
        
        // Refresh tampilan
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardDashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        labelJudulKlinik = new javax.swing.JLabel();
        labelIconKlinik = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDashboard = new javax.swing.JButton();
        btnInformasiDokter = new javax.swing.JButton();
        btnManajemenPasien = new javax.swing.JButton();
        btnManajemenJadwal = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btnRegistrasiKunjungan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard - Klinik Sehat Selalu");

        panelSidebar.setBackground(new java.awt.Color(34, 40, 49));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 389));

        labelJudulKlinik.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelJudulKlinik.setForeground(new java.awt.Color(255, 255, 255));
        labelJudulKlinik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudulKlinik.setText("<html>KLINIK<br>SEHAT SELALU</html>");

        labelIconKlinik.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelIconKlinik.setForeground(new java.awt.Color(255, 255, 255));
        labelIconKlinik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconKlinik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarKlinik.png"))); // NOI18N

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDashboard.setForeground(java.awt.Color.white);
        btnDashboard.setText("🏠  Dashboard");
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnInformasiDokter.setBackground(new java.awt.Color(255, 255, 255));
        btnInformasiDokter.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnInformasiDokter.setForeground(java.awt.Color.white);
        btnInformasiDokter.setText("👨‍  ️️Informasi Dokter");
        btnInformasiDokter.setBorderPainted(false);
        btnInformasiDokter.setContentAreaFilled(false);
        btnInformasiDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformasiDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInformasiDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformasiDokterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformasiDokterMouseExited(evt);
            }
        });
        btnInformasiDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformasiDokterActionPerformed(evt);
            }
        });

        btnManajemenPasien.setBackground(new java.awt.Color(255, 255, 255));
        btnManajemenPasien.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnManajemenPasien.setForeground(java.awt.Color.white);
        btnManajemenPasien.setText("👤  Manajemen Pasien");
        btnManajemenPasien.setBorderPainted(false);
        btnManajemenPasien.setContentAreaFilled(false);
        btnManajemenPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajemenPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManajemenPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManajemenPasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManajemenPasienMouseExited(evt);
            }
        });
        btnManajemenPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenPasienActionPerformed(evt);
            }
        });

        btnManajemenJadwal.setBackground(new java.awt.Color(255, 255, 255));
        btnManajemenJadwal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnManajemenJadwal.setForeground(java.awt.Color.white);
        btnManajemenJadwal.setText("📅  Manajemen Jadwal");
        btnManajemenJadwal.setBorderPainted(false);
        btnManajemenJadwal.setContentAreaFilled(false);
        btnManajemenJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManajemenJadwal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManajemenJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManajemenJadwalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManajemenJadwalMouseExited(evt);
            }
        });
        btnManajemenJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenJadwalActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(220, 53, 69));
        btn_logout.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("[➜  Logout");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btnRegistrasiKunjungan.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrasiKunjungan.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRegistrasiKunjungan.setForeground(java.awt.Color.white);
        btnRegistrasiKunjungan.setText("📝 Registrasi Kunjungan");
        btnRegistrasiKunjungan.setContentAreaFilled(false);
        btnRegistrasiKunjungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrasiKunjungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrasiKunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrasiKunjunganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrasiKunjunganMouseExited(evt);
            }
        });
        btnRegistrasiKunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiKunjunganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_logout)
                            .addGroup(panelSidebarLayout.createSequentialGroup()
                                .addComponent(labelIconKlinik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelJudulKlinik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrasiKunjungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManajemenPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManajemenJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInformasiDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelIconKlinik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJudulKlinik, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrasiKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManajemenPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManajemenJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInformasiDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(panelContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        // Ambil CardLayout dari panelContent
        CardLayout cl = (CardLayout) panelContent.getLayout();

        // Tampilkan "kartu" dengan nama "cardDashboard"
        cl.show(panelContent, "cardDashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnManajemenJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenJadwalActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardJadwal");
    }//GEN-LAST:event_btnManajemenJadwalActionPerformed

    private void btnInformasiDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformasiDokterActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardDokter");
    }//GEN-LAST:event_btnInformasiDokterActionPerformed

    private void btnManajemenPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenPasienActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardPasien");
    }//GEN-LAST:event_btnManajemenPasienActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        // Tampilkan konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin logout?", 
                "Konfirmasi Logout", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);

        if (pilihan == JOptionPane.YES_OPTION) {
            // Buka kembali jendela Login
            new JFrame_Login().setVisible(true);

            // Tutup dashboard ini
            this.dispose(); 
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        // TODO add your handling code here:
        btnDashboard.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        // TODO add your handling code here:
        btnDashboard.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnManajemenPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenPasienMouseEntered
        // TODO add your handling code here:
        btnManajemenPasien.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnManajemenPasienMouseEntered

    private void btnManajemenPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenPasienMouseExited
        // TODO add your handling code here:
        btnManajemenPasien.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnManajemenPasienMouseExited

    private void btnInformasiDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiDokterMouseEntered
        // TODO add your handling code here:
        btnInformasiDokter.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnInformasiDokterMouseEntered

    private void btnInformasiDokterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiDokterMouseExited
        // TODO add your handling code here:
        btnInformasiDokter.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnInformasiDokterMouseExited

    private void btnManajemenJadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenJadwalMouseEntered
        // TODO add your handling code here:
        btnManajemenJadwal.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnManajemenJadwalMouseEntered

    private void btnManajemenJadwalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManajemenJadwalMouseExited
        // TODO add your handling code here:
        btnManajemenJadwal.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnManajemenJadwalMouseExited

    private void btnRegistrasiKunjunganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrasiKunjunganMouseEntered
        // TODO add your handling code here:
        btnRegistrasiKunjungan.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnRegistrasiKunjunganMouseEntered

    private void btnRegistrasiKunjunganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrasiKunjunganMouseExited
        // TODO add your handling code here:
        btnRegistrasiKunjungan.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnRegistrasiKunjunganMouseExited

    private void btnRegistrasiKunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiKunjunganActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardRegistrasiKunjungan");
//       java.awt.CardLayout cl = (java.awt.CardLayout) panelContent.getLayout();
//        cl.show(panelContent, "cardRegistrasi");
        
    }//GEN-LAST:event_btnRegistrasiKunjunganActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Main_Resepsionis().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInformasiDokter;
    private javax.swing.JButton btnManajemenJadwal;
    private javax.swing.JButton btnManajemenPasien;
    private javax.swing.JButton btnRegistrasiKunjungan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelIconKlinik;
    private javax.swing.JLabel labelJudulKlinik;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
