/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;
import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.Frame;

/**
 *
 * @author USER
 */
public final class JPanel_Manajemen_Jadwal extends javax.swing.JPanel {
    
    /**
     * Creates new form JPanel_Manajemen_Jadwal
     */
    public JPanel_Manajemen_Jadwal() {
        initComponents();
        
        
        tblJadwal.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblJadwal.getTableHeader().setOpaque(false);
        tblJadwal.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblJadwal.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih

        loadDataJadwal();
    }
    public void loadDataJadwal() {
        
    }
    public void loadDataJadwal(String searchTerm) {
//        // 1. Dapatkan model tabel
//        DefaultTableModel model = (DefaultTableModel) tblJadwal.getModel();
//
//        // 2. Kosongkan tabel (hapus baris lama)
//        model.setRowCount(0);
//
//        try {
            // Ambil filter hari
//            String filterHari = comboFilterHari.getSelectedItem().toString();
//
//            // Query dasar dengan JOIN
//            String sql = "SELECT j.id_jadwal, d.nama_dokter, d.spesialisasi, j.hari, j.jam_mulai, j.jam_selesai " +
//                         "FROM jadwal j " +
//                         "JOIN dokter d ON j.id_dokter = d.id_dokter ";
//
//            // Tambahkan filter jika bukan "Semua Hari"
//            if (!filterHari.equals("Semua Hari")) {
//                sql += "WHERE j.hari = '" + filterHari + "'";
//            }
//
    //        // 5. Gunakan try-with-resources untuk koneksi
    //        try (Connection conn = Koneksi.getConnection(); // Asumsi Anda punya kelas Koneksi
    //             PreparedStatement pstmt = conn.prepareStatement(sql)) {
    //
    //            // 6. Set parameter pencarian jika ada
    //            if (searchTerm != null && !searchTerm.trim().isEmpty()) {
    //                String likeTerm = "%" + searchTerm + "%";
    //                pstmt.setString(1, likeTerm);
    //                pstmt.setString(2, likeTerm);
    //            }
    //
    //            // 7. Eksekusi query
    //            try (ResultSet rs = pstmt.executeQuery()) {
    //                // 8. Looping hasil dan tambahkan ke model tabel
    //                while (rs.next()) {
//                            model.addRow(new Object[]{
//                                rs.getString("id_jadwal"),
//                                rs.getString("nama_dokter"),
//                                rs.getString("spesialisasi"),
//                                rs.getString("hari"),
//                                rs.getString("jam_mulai"),
//                                rs.getString("jam_selesai")
//                            });
//                        }
    //            }
    //
    //        } catch (Exception e) {
    //            JOptionPane.showMessageDialog(this, 
    //                    "Gagal memuat data jadwal: " + e.getMessage(), 
    //                    "Error Database", 
    //                    JOptionPane.ERROR_MESSAGE);
    //            e.printStackTrace(); // Tampilkan error di console untuk debug
    //        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKontrol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboFilterHari = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Manajemen Jadwal Praktik");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelKontrol.setBackground(new java.awt.Color(255, 255, 255));

        btnTambah.setBackground(new java.awt.Color(50, 120, 220));
        btnTambah.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("➕  Tambah Jadwal Baru");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 130, 0));
        btnEdit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("📝  Edit Jadwal");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(220, 53, 69));
        btnHapus.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("❌  Hapus Jadwal");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblJadwal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"P001", "ABCD", "20-12-2001", "Laki-laki", "Jl. Abc", "0813"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "Nama Dokter", "Spesialisasi", "Hari", "Jam Mulai", "Jam Selesai"
            }
        ));
        tblJadwal.setGridColor(new java.awt.Color(224, 224, 224));
        tblJadwal.setRowHeight(30);
        tblJadwal.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblJadwal.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblJadwal.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblJadwal);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Filter Hari");

        comboFilterHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu" }));
        comboFilterHari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFilterHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterHariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabel)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFilterHari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboFilterHari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblJudul)
                        .addGap(0, 537, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        JDialog_Form_Jadwal formJadwal = new JDialog_Form_Jadwal(null, true, this);
        formJadwal.setVisible(true);
        loadDataJadwal();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblJadwal.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Pilih data jadwal yang ingin Anda edit terlebih dahulu.", 
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
//            return; // Hentikan eksekusi
        }

        // 3. Ambil ID Pasien dari kolom pertama (index 0)
        String idJadwal = tblJadwal.getValueAt(selectedRow, 0).toString();

        JDialog_Form_Jadwal formJadwal = new JDialog_Form_Jadwal(null, true, this, idJadwal);
        formJadwal.setVisible(true);
        loadDataJadwal();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblJadwal.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Pilih data jadwal yang ingin Anda hapus.", 
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil ID dan Nama untuk konfirmasi
        String idJadwal = tblJadwal.getValueAt(selectedRow, 0).toString();
        String namaDokter = tblJadwal.getValueAt(selectedRow, 1).toString();

        // 4. Tampilkan dialog konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data jadwal:\n" + namaDokter + " (ID: " + idJadwal + ")?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // 5. Cek jika pengguna menekan "Ya"
        if (pilihan == JOptionPane.YES_OPTION) {
            // 6. Lakukan operasi database
            String sql = "DELETE FROM jadwal WHERE jadwal_id = ?";

//            try (Connection conn = KoneksiDatabase.getConnection();
//                 PreparedStatement pstmt = conn.prepareStatement(sql)) {
//
//                pstmt.setString(1, idJadwal);
//
//                // 7. Eksekusi delete
//                int rowsAffected = pstmt.executeUpdate();
//
//                if (rowsAffected > 0) {
//                    JOptionPane.showMessageDialog(this, 
//                            "Data jadwal berhasil dihapus.", 
//                            "Sukses", 
//                            JOptionPane.INFORMATION_MESSAGE);
//
//                    // 8. Muat ulang data (dan bersihkan pencarian)
////                    txtCari.setText(""); // Bersihkan field pencarian
////                    loadDataJadwal(null); // Muat ulang semua data
//                } else {
//                    JOptionPane.showMessageDialog(this, 
//                            "Data jadwal tidak ditemukan (mungkin sudah dihapus).", 
//                            "Info", 
//                            JOptionPane.INFORMATION_MESSAGE);
//                }
//
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, 
//                        "Gagal menghapus data: " + e.getMessage(), 
//                        "Error Database", 
//                        JOptionPane.ERROR_MESSAGE);
////                e.printStackTrace();
//            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void comboFilterHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterHariActionPerformed
        // TODO add your handling code here:
        loadDataJadwal();
    }//GEN-LAST:event_comboFilterHariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> comboFilterHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tblJadwal;
    // End of variables declaration//GEN-END:variables
}
