/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;
import Database.KoneksiDatabase;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public final class JPanel_Manajemen_Jadwal extends javax.swing.JPanel {
    
    // Atribut
    Connection conn = KoneksiDatabase.getConnection();
    
    /**
     * Creates new form JPanel_Manajemen_Jadwal
     */
    public JPanel_Manajemen_Jadwal() {
        initComponents();
        
        
        tblJadwal.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblJadwal.getTableHeader().setOpaque(false);
        tblJadwal.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblJadwal.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih

        loadDataJadwal("Semua Hari");
    }
    
    
    
    public void loadDataJadwal(String searchTerm) {
//       // 1. Siapkan Model Tabel
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblJadwal.getModel();
        model.setRowCount(0); // Bersihkan data lama

        // 2. Query TRIPLE JOIN (Jadwal -> Dokter -> User)
        // Tujuannya: Mengambil nama lengkap dokter dari tabel user berdasarkan jadwal
        String sql = "SELECT j.jadwal_id, u.nama_lengkap, d.spesialisasi, j.hari, j.jam_mulai, j.jam_selesai " +
                     "FROM jadwal_praktik j " +
                     "JOIN dokter d ON j.dokter_id = d.dokter_id " +
                     "JOIN user u ON d.user_id = u.user_id ";

        // 3. Logika Filter Hari
        // Jika filter BUKAN "Semua Hari", tambahkan kondisi WHERE
        boolean isFilterActive = searchTerm != null && !searchTerm.equalsIgnoreCase("Semua Hari");

        if (isFilterActive) {
            sql += "WHERE j.hari = ? ";
        }

        // Urutkan biar rapi (Senin, Selasa... secara alfabet atau jam)
        sql += "ORDER BY j.hari, j.jam_mulai ASC";

        // 4. Eksekusi Query
        try (PreparedStatement stmt = this.conn.prepareStatement(sql)) {

            if (isFilterActive) {
                stmt.setString(1, searchTerm);
            }

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    // Format Jam agar tampil HH:mm (tanpa detik) - Opsional
                    String jamMulai = rs.getString("jam_mulai").substring(0, 5); 
                    String jamSelesai = rs.getString("jam_selesai").substring(0, 5);

                    Object[] row = {
                        rs.getInt("jadwal_id"),
                        rs.getString("nama_lengkap"),  // Dari tabel User
                        rs.getString("spesialisasi"),  // Dari tabel Dokter
                        rs.getString("hari"),
                        jamMulai,
                        jamSelesai
                    };
                    model.addRow(row);
                }
            }

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat jadwal: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKontrol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboFilterHari = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Manajemen Jadwal Praktik");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelKontrol.setBackground(new java.awt.Color(255, 255, 255));

        btnTambah.setBackground(new java.awt.Color(50, 120, 220));
        btnTambah.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("➕  Tambah Jadwal Baru");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 130, 0));
        btnEdit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("📝  Edit Jadwal");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(220, 53, 69));
        btnHapus.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("❌  Hapus Jadwal");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblJadwal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"P001", "ABCD", "20-12-2001", "Laki-laki", "Jl. Abc", "0813"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "Nama Dokter", "Spesialisasi", "Hari", "Jam Mulai", "Jam Selesai"
            }
        ));
        tblJadwal.setGridColor(new java.awt.Color(224, 224, 224));
        tblJadwal.setRowHeight(30);
        tblJadwal.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblJadwal.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblJadwal.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblJadwal);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Filter Hari");

        comboFilterHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu" }));
        comboFilterHari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFilterHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterHariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabel)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFilterHari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboFilterHari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(panelKontrol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(0, 512, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(panelKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        JDialog_Form_Jadwal formJadwal = new JDialog_Form_Jadwal(null, true, this);
        formJadwal.setVisible(true);
        String filterSaatIni = comboFilterHari.getSelectedItem().toString();
        
        loadDataJadwal(filterSaatIni);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblJadwal.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Pilih data jadwal yang ingin Anda edit terlebih dahulu.", 
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
//            return; // Hentikan eksekusi
        }

        // 3. Ambil ID Pasien dari kolom pertama (index 0)
        String idJadwal = tblJadwal.getValueAt(selectedRow, 0).toString();

        JDialog_Form_Jadwal formJadwal = new JDialog_Form_Jadwal(null, true, this, idJadwal);
        formJadwal.setVisible(true);
        
        String filterSaatIni = comboFilterHari.getSelectedItem().toString();
        loadDataJadwal(filterSaatIni);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblJadwal.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Pilih data jadwal yang ingin Anda hapus.", 
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil ID dan Nama untuk konfirmasi
        String idJadwal = tblJadwal.getValueAt(selectedRow, 0).toString();
        String namaDokter = tblJadwal.getValueAt(selectedRow, 1).toString();

        // 4. Tampilkan dialog konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data jadwal:\n" + namaDokter + " (ID: " + idJadwal + ")?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // 5. Cek jika pengguna menekan "Ya"
        if (pilihan == JOptionPane.YES_OPTION) {
            // 6. Lakukan operasi database
            String sql = "DELETE FROM jadwal_praktik WHERE jadwal_id = ?";
            
            try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {

                pstmt.setString(1, idJadwal);

                // 7. Eksekusi delete
                int rowsAffected = pstmt.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, 
                            "Data jadwal berhasil dihapus.", 
                            "Sukses", 
                            JOptionPane.INFORMATION_MESSAGE);

                    // 8. Muat ulang data (dan bersihkan pencarian)
                       String filterSaatIni = comboFilterHari.getSelectedItem().toString();
                       loadDataJadwal(filterSaatIni);
                } else {
                    JOptionPane.showMessageDialog(this, 
                            "Data jadwal tidak ditemukan (mungkin sudah dihapus).", 
                            "Info", 
                            JOptionPane.INFORMATION_MESSAGE);
                }


            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, 
                        "Gagal menghapus data: " + e.getMessage(), 
                        "Error Database", 
                        JOptionPane.ERROR_MESSAGE);
//                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void comboFilterHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterHariActionPerformed
        // TODO add your handling code here:
        String hariDipilih = comboFilterHari.getSelectedItem().toString();
    
        // Panggil method load tadi
        loadDataJadwal(hariDipilih);
    }//GEN-LAST:event_comboFilterHariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> comboFilterHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tblJadwal;
    // End of variables declaration//GEN-END:variables
}
