/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;
//import Main.Database.Koneksi;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
//import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public final class JPanel_Informasi_Dokter extends javax.swing.JPanel {
    
    private final ImageIcon searchIcon = new ImageIcon(getClass().getResource("/search.png"));
    
    /**
     * Creates new form JPanel_Manajemen_Dokter
     */
    public JPanel_Informasi_Dokter() {
        initComponents();
        
        txtCari.putClientProperty("JTextField.placeholderText", "Cari dokter...");
        
        // Menjadwalkan update gambar setelah ukuran tombol tersedia
        SwingUtilities.invokeLater(() -> {
            // Sesuaikan ukuran gambar
            btnCari.setIcon(new ImageIcon(searchIcon.getImage().getScaledInstance(btnCari.getWidth(), btnCari.getHeight(), Image.SCALE_SMOOTH)));
        });
        
        tblDokter.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12));
        tblDokter.getTableHeader().setOpaque(false);
        tblDokter.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblDokter.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih

        loadDataDokter(null);
    }
    
    public void loadDataDokter() {
        
    }
    public void loadDataDokter(String searchTerm) {
//        // 1. Dapatkan model tabel
//        DefaultTableModel model = (DefaultTableModel) tblDokter.getModel();
//
//        // 2. Kosongkan tabel (hapus baris lama)
//        model.setRowCount(0);
//
//        // 3. Buat query SQL dasar
//        String sql = "SELECT id_dokter, nama_dokter, spesialisasi, no_telepon FROM dokter";
//
//        // 4. Tambahkan kondisi WHERE jika ada searchTerm
//        if (searchTerm != null && !searchTerm.trim().isEmpty()) {
//            sql += " WHERE nama_dokter LIKE ? OR dokter_id LIKE ?";
//        }
//
//        // 5. Gunakan try-with-resources untuk koneksi
//        try (Connection conn = Koneksi.getConnection(); // Asumsi Anda punya kelas Koneksi
//             PreparedStatement pstmt = conn.prepareStatement(sql)) {
//
//            // 6. Set parameter pencarian jika ada
//            if (searchTerm != null && !searchTerm.trim().isEmpty()) {
//                String likeTerm = "%" + searchTerm + "%";
//                pstmt.setString(1, likeTerm);
//                pstmt.setString(2, likeTerm);
//            }
//
//            // 7. Eksekusi query
//            try (ResultSet rs = pstmt.executeQuery()) {
//                // 8. Looping hasil dan tambahkan ke model tabel
//                while (rs.next()) {
//                        model.addRow(new Object[]{
//                            rs.getString("id_dokter"),
//                            rs.getString("nama_dokter"),
//                            rs.getString("spesialisasi"),
//                            rs.getString("no_telepon")
//                        });
//                    }
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, 
//                    "Gagal memuat data dokter: " + e.getMessage(), 
//                    "Error Database", 
//                    JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace(); // Tampilkan error di console untuk debug
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKontrol = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Informasi Dokter Klinik");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelKontrol.setBackground(new java.awt.Color(255, 255, 255));

        btnCari.setBackground(new java.awt.Color(75, 167, 87));
        btnCari.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.setPreferredSize(new java.awt.Dimension(40, 40));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblDokter.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"D001", "dr. Abc", "Umum", "08123456781"},
                {"D002", "dr. Abcd, Sp.A", "Anak", "08123456782"},
                {"D003", "drg. Abcde", "Gigi", "08123456783"},
                {"D004", "dr. Abcdef, Sp.KK", "Kulit dan Kelamin", "08123456784"},
                {"D005", "dr. Abcdefg Sp.OG", "Kandungan dan Kebidanan", "08123456785"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama Lengkap", "Spesialisasi", "No. Telepon"
            }
        ));
        tblDokter.setGridColor(new java.awt.Color(224, 224, 224));
        tblDokter.setRowHeight(30);
        tblDokter.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblDokter.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblDokter.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblDokter);

        txtCari.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKontrolLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblJudul)
                        .addGap(0, 581, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        // 1. Ambil kata kunci dari JTextField
        String searchTerm = txtCari.getText();

        // 2. Panggil method loadDataDokter dengan kata kunci tersebut
        loadDataDokter(searchTerm);
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
