/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;
import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;

/**
 *
 * @author USER
 */
public final class JPanel_Manajemen_Pasien extends javax.swing.JPanel {
    
    // Atribut
    Connection conn = KoneksiDatabase.getConnection();
    
    /**
     * Creates new form JPanel_Manajemen_Pasien
     */
    public JPanel_Manajemen_Pasien() {
        initComponents();
              
        txtCari.putClientProperty("JTextField.placeholderText", "Cari pasien...");
        
        tblPasien.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblPasien.getTableHeader().setOpaque(false);
        tblPasien.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblPasien.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih

        loadDataToTable();
    }
    public void loadDataToTable() {
        loadDataToTable(null);  
    }
    public void loadDataToTable(String searchTerm) {
        
           javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPasien.getModel();
            model.setRowCount(0); // Bersihkan tabel

            // 1. Buat Query yang dinamis
            String sql = "SELECT * FROM pasien";
            if (searchTerm != null && !searchTerm.trim().isEmpty()) {
             sql += " WHERE nama_pasien LIKE ? OR pasien_id LIKE ?";
           }
        sql += " ORDER BY pasien_id DESC"; // Tambahkan pengurutan
        
        try (PreparedStatement stmt = this.conn.prepareStatement(sql)) {

            // 2. Jika ada kata kunci pencarian, masukkan ke parameter
            if (searchTerm != null && !searchTerm.trim().isEmpty()) {
                String likeValue = "%" + searchTerm + "%";
                stmt.setString(1, likeValue);
                stmt.setString(2, likeValue);
        }

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    Object[] row = {
                        rs.getString("pasien_id"),
                        rs.getString("nama_pasien"),
                        rs.getDate("tanggal_lahir"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("alamat"),
                        rs.getString("no_telepon"),
                        rs.getString("golongan_darah"),
                        rs.getString("pekerjaan"),
                        rs.getString("nama_kerabat"),
                        rs.getString("no_telp_kerabat"),
                        rs.getString("status_pernikahan")

                    };
                    model.addRow(row);
                }
            }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat tabel: " + e.getMessage());
            e.printStackTrace();
        }



     }
    
    

    /**
     * 
     * 
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKontrol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        lblJudul1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_riwayat_kunjungan = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Manajemen Data Pasien");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelKontrol.setBackground(new java.awt.Color(255, 255, 255));

        btnTambah.setBackground(new java.awt.Color(50, 120, 220));
        btnTambah.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("➕  Tambah Pasien");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 130, 0));
        btnEdit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("📝  Edit Data");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(220, 53, 69));
        btnHapus.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("❌  Hapus Data");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(75, 167, 87));
        btnCari.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnCari.setForeground(new java.awt.Color(0, 0, 0));
        btnCari.setText("🔍");
        btnCari.setBorder(null);
        btnCari.setBorderPainted(false);
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblPasien.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"P001", "ABCD", "20-12-2001", "Laki-laki", "Jl. Abc", "0813", null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pasien", "Nama Lengkap", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No. Telepon", "Golongan Darah", "Pekerjaan", "Nama Kerabat", "No. Telp Kerabat", "Status"
            }
        ));
        tblPasien.setGridColor(new java.awt.Color(224, 224, 224));
        tblPasien.setRowHeight(30);
        tblPasien.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblPasien.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblPasien.setShowGrid(true);
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        scrollPaneTabel.setViewportView(tblPasien);

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        lblJudul1.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        lblJudul1.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul1.setText("Riwayat Pasien");

        tabel_riwayat_kunjungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Tanggal Kunjungan", "Nama Dokter", "Poli"
            }
        ));
        jScrollPane1.setViewportView(tabel_riwayat_kunjungan);

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(lblJudul1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJudul1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(panelKontrol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(0, 563, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(panelKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        JDialog_Form_Pasien formPasien = new JDialog_Form_Pasien(null, true, this); // null = parent, true = modal
        formPasien.setVisible(true);

        // Setelah form ditutup, muat ulang data di tabel
        loadDataToTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        

            int baris = tblPasien.getSelectedRow();
    
            if (baris != -1) {
            // Ambil ID Pasien dari kolom 0 tabel
            String idPasien = tblPasien.getValueAt(baris, 0).toString();
        
            // Buka Dialog dengan constructor Edit (Constructor ke-2)
            // 'this' merujuk pada Panel, 'parent' biasanya diambil dari Frame utama
            java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            JDialog_Form_Pasien dialog = new JDialog_Form_Pasien(parent, true, this, idPasien);
            dialog.setVisible(true);
            } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu!");
            }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblPasien.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Pilih data pasien yang ingin Anda hapus.", 
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil ID dan Nama untuk konfirmasi
        String idPasien = tblPasien.getValueAt(selectedRow, 0).toString();
        String namaPasien = tblPasien.getValueAt(selectedRow, 1).toString();

        // 4. Tampilkan dialog konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus data pasien:\n" + namaPasien + " (ID: " + idPasien + ")?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        
        
        // 4. Jika user klik YES, baru eksekusi hapus
    if (pilihan == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM pasien WHERE pasien_id = ?";

        try (PreparedStatement stmt = this.conn.prepareStatement(sql)) {

            stmt.setString(1, idPasien);

            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data pasien berhasil dihapus!");

                // 5. Refresh tabel agar data yang dihapus hilang dari tampilan
                loadDataToTable(); 

                // Opsional: Bersihkan field pencarian jika ada
                txtCari.setText("");
            }
        } catch (SQLIntegrityConstraintViolationException e) {
            // ERROR KHUSUS: Jika pasien sudah punya riwayat kunjungan (Foreign Key)
            JOptionPane.showMessageDialog(this, """
                                                Gagal menghapus data!
                                                Pasien ini memiliki riwayat kunjungan/resep.
                                                Hapus data kunjungan terkait terlebih dahulu.""", 
                "Terproteksi Database", 
                JOptionPane.ERROR_MESSAGE);
                
        } catch (SQLException e) {
            // Error database umum lainnya
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan database: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        // 1. Ambil kata kunci dari JTextField
        String searchTerm = txtCari.getText();

        // 2. Panggil method loadDataToTable dengan kata kunci tersebut
        loadDataToTable(searchTerm);
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        // TODO add your handling code here:
        int baris = tblPasien.getSelectedRow();
    
        if (baris != -1) {
            // 2. Ambil ID Pasien dari kolom ke-0 (sesuaikan dengan posisi kolom ID di tabel Anda)
            // Pastikan kolom ke-0 adalah ID Pasien (103, 102, dst pada gambar)
            String idPasien = tblPasien.getValueAt(baris, 0).toString();

            // 3. Panggil method untuk isi tabel bawah
            tampilkanRiwayatPasien(idPasien);
        }
        
    }//GEN-LAST:event_tblPasienMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tabel_riwayat_kunjungan;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables



private void tampilkanRiwayatPasien(String idPasien) {
    // 1. Siapkan Model Tabel
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Tanggal Kunjungan");
    model.addColumn("Nama Dokter");
    model.addColumn("Poli"); 

    try {
        int no = 1;
        
        // 2. Query SQL dengan DOUBLE JOIN (Kunjungan -> Dokter -> User)
        String sql = "SELECT k.tanggal_kunjungan, u.nama_lengkap, d.spesialisasi " + 
                     "FROM kunjungan k " +
                     "JOIN dokter d ON k.dokter_id = d.dokter_id " +
                     "JOIN user u ON d.user_id = u.user_id " +
                     "WHERE k.pasien_id = '" + idPasien + "' " +
                     "ORDER BY k.tanggal_kunjungan DESC";
        
        try (Statement stm = this.conn.createStatement();
        ResultSet res = stm.executeQuery(sql)) {

            // 3. Masukkan data ke tabel
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString("tanggal_kunjungan"),
                    res.getString("nama_lengkap"), // Ini mengambil dari tabel user
                    res.getString("spesialisasi")     // Asumsi kolom poli ada di tabel dokter
                });
            }

            tabel_riwayat_kunjungan.setModel(model);

            // Atur lebar kolom (Opsional)
            tabel_riwayat_kunjungan.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabel_riwayat_kunjungan.getColumnModel().getColumn(1).setPreferredWidth(120);
        }
    } catch (SQLException e) {
        System.out.println("Error Load Riwayat: " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat riwayat: " + e.getMessage());
    }
}

}
