/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author USER
 */
public class JPanel_Registrasi_Kunjungan extends javax.swing.JPanel {
    
    private String loggedInResepsionisId;
    private String selectedPasienId = null; // Menyimpan ID pasien yg ditemukan
    
    /**
     * Creates new form JPanel_Registrasi_Kunjungan
     */
    public JPanel_Registrasi_Kunjungan() {
        initComponents();
        txtCariPasien.putClientProperty("JTextField.placeholderText", "Ketik ID atau Nama...");
        
        // --- TAMBAHKAN BARIS INI UNTUK MENYEMBUNYIKANNYA ---
        panelInfoPasien.setVisible(false); 
        // ---

        initForm();
    }
    
    // Kelas helper untuk JComboBox
    class DokterItem {
        public String id; public String nama; public String spesialisasi;
        public DokterItem(String id, String nama, String spes) { this.id=id; this.nama=nama; this.spesialisasi=spes; }
        @Override public String toString() { return nama; }
    }
    
    public JPanel_Registrasi_Kunjungan(String resepsionisId) {
        initComponents();
        this.loggedInResepsionisId = resepsionisId;

        initForm(); // Panggil method kustom
    }
    
    private void initForm() {
        // 1. Sembunyikan/Nonaktifkan komponen
        panelInfoPasien.setVisible(false);
        panelStep2.setEnabled(false);
        btnDaftarkan.setEnabled(false);

        // 2. Format JSpinner
//        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(spinnerBiayaJasa, "#,##0");
//        spinnerBiayaJasa.setEditor(editor);

        // 3. Muat data dokter ke JComboBox
        loadDokterComboBox();

        // 4. Tambahkan listener ke comboDokter
        comboDokter.addActionListener(e -> {
            DokterItem item = (DokterItem) comboDokter.getSelectedItem();
            if (item != null) {
//                label_dokter.setText(item.spesialisasi);
            }
        });
    }

    private void loadDokterComboBox() {
        // SQL: "SELECT id_dokter, nama_dokter, spesialisasi FROM dokter"
        // ... (Eksekusi query) ...
        // while (rs.next()) {
        //    comboDokter.addItem(new DokterItem(rs.getString("id_dokter"), rs.getString("nama_dokter"), rs.getString("spesialisasi")));
        // }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelStep1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCariPasien = new javax.swing.JTextField();
        btnCariPasien = new javax.swing.JButton();
        panelInfoPasien = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_tgl_lahir = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_alamat = new javax.swing.JLabel();
        panelStep2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboDokter = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        label_dokter1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDaftarkan = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Registrasi Kunjungan Pasien");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Daftarkan pasien yang berkunjung hari ini ke antrean dokter.");

        panelStep1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Cari (ID atau Nama Pasien):");

        txtCariPasien.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnCariPasien.setBackground(new java.awt.Color(50, 120, 220));
        btnCariPasien.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCariPasien.setForeground(java.awt.Color.white);
        btnCariPasien.setText("🔍  Cari");
        btnCariPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPasienActionPerformed(evt);
            }
        });

        panelInfoPasien.setBackground(new java.awt.Color(245, 245, 245));
        panelInfoPasien.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Data Pasien"));
        panelInfoPasien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        labelID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelID.setForeground(java.awt.Color.black);
        labelID.setText("ID Pasien:");

        label_id.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_id.setForeground(java.awt.Color.black);
        label_id.setText("-");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Nama:");

        label_nama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_nama.setForeground(java.awt.Color.black);
        label_nama.setText("-");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Tgl. Lahir:");

        label_tgl_lahir.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_tgl_lahir.setForeground(java.awt.Color.black);
        label_tgl_lahir.setText("-");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Alamat");

        label_alamat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_alamat.setForeground(java.awt.Color.black);
        label_alamat.setText("-");

        javax.swing.GroupLayout panelInfoPasienLayout = new javax.swing.GroupLayout(panelInfoPasien);
        panelInfoPasien.setLayout(panelInfoPasienLayout);
        panelInfoPasienLayout.setHorizontalGroup(
            panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPasienLayout.createSequentialGroup()
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelID)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInfoPasienLayout.setVerticalGroup(
            panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelStep1Layout = new javax.swing.GroupLayout(panelStep1);
        panelStep1.setLayout(panelStep1Layout);
        panelStep1Layout.setHorizontalGroup(
            panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStep1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelStep1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariPasien))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStep1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCariPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelStep1Layout.setVerticalGroup(
            panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStep1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCariPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfoPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelStep2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        panelStep2.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Pilih Poli");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Dokter");

        comboDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter Kliniks", "Wahyu Triadi", "Amelia Devi" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poli Umum", "Poli Gigi", "Poli Anak", "Poli Mata", "Poli THT" }));

        javax.swing.GroupLayout panelStep2Layout = new javax.swing.GroupLayout(panelStep2);
        panelStep2.setLayout(panelStep2Layout);
        panelStep2Layout.setHorizontalGroup(
            panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStep2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelStep2Layout.setVerticalGroup(
            panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStep2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        label_dokter1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Estimasi Nomor Antrian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(186, Short.MAX_VALUE)
                    .addComponent(label_dokter1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(label_dokter1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        btnDaftarkan.setBackground(new java.awt.Color(25, 135, 84));
        btnDaftarkan.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnDaftarkan.setForeground(java.awt.Color.white);
        btnDaftarkan.setText("✚  Daftarkan Pasien ke Antrean");
        btnDaftarkan.setEnabled(false);
        btnDaftarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStep1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelStep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDaftarkan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblJudul))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelStep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelStep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnDaftarkan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPasienActionPerformed
        // TODO add your handling code here:
        cariPasien();
       
        // }
    }//GEN-LAST:event_btnCariPasienActionPerformed

    private void btnDaftarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarkanActionPerformed
        // TODO add your handling code here:
        // 1. Validasi
        if (this.selectedPasienId == null) {
            JOptionPane.showMessageDialog(this, "Kesalahan: Tidak ada pasien terpilih.");
            return;
        }

        // 2. Ambil semua data
        String pasienId = this.selectedPasienId;
        String resepsionisId = this.loggedInResepsionisId;
        DokterItem dokter = (DokterItem) comboDokter.getSelectedItem();
        String dokterId = dokter.id;
//        int biayaJasa = (Integer) spinnerBiayaJasa.getValue();

        // 3. Konfirmasi
//        int pilihan = JOptionPane.showConfirmDialog(this, 
//                "Daftarkan pasien:\n" + label_nama.getText() + "\nKe Dokter: " + dokter.nama + "\nBiaya Jasa: Rp. " +
//                "Konfirmasi Pendaftaran", JOptionPane.YES_NO_OPTION);

//        if (pilihan == JOptionPane.NO_OPTION) {
//            return; // Batal
//        }

        // 4. Eksekusi TRANSAKSI DATABASE
        // Connection conn = Koneksi.getConnection();
        // PreparedStatement pstmtKunjungan = null;
        // PreparedStatement pstmtBayar = null;

        try {
            // conn.setAutoCommit(false); // Mulai Transaksi

            // --- Query 1: INSERT ke Kunjungan ---
//            String sqlKunjungan = "INSERT INTO kunjungan (pasien_id, dokter_id, user_id_admin, tanggal_kunjungan, status_kunjungan) " +
//                                  "VALUES (?, ?, ?, NOW(), 'Menunggu')";
            // pstmtKunjungan = conn.prepareStatement(sqlKunjungan, Statement.RETURN_GENERATED_KEYS);
            // pstmtKunjungan.setString(1, pasienId);
            // ... (set parameter lain) ...
            // pstmtKunjungan.executeUpdate();

            // Ambil ID Kunjungan yang baru dibuat
            // ResultSet rsKeys = pstmtKunjungan.getGeneratedKeys();
            // String kunjunganIdBaru = "";
            // if (rsKeys.next()) { kunjunganIdBaru = rsKeys.getString(1); }

            // --- Query 2: INSERT ke Pembayaran ---
//            String sqlBayar = "INSERT INTO pembayaran (kunjungan_id, total_biaya_jasa, total_biaya_obat, total_bayar) " +
//                              "VALUES (?, ?, 0, ?)";
            // pstmtBayar = conn.prepareStatement(sqlBayar);
            // pstmtBayar.setString(1, kunjunganIdBaru);
            // pstmtBayar.setInt(2, biayaJasa);
            // pstmtBayar.setInt(3, biayaJasa); // Total bayar awal = biaya jasa
            // pstmtBayar.executeUpdate();

            // conn.commit(); // Selesaikan Transaksi

            JOptionPane.showMessageDialog(this, "Pasien berhasil didaftarkan ke antrean!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            resetForm();

        } catch (Exception e) {
            // try { conn.rollback(); } catch (SQLException ex) { ... } // Batalkan jika gagal
            JOptionPane.showMessageDialog(this, "Gagal menyimpan ke database: " + e.getMessage(), "Error Transaksi", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Tutup semua PreparedStatement dan setAutoCommit(true)
        }
    }//GEN-LAST:event_btnDaftarkanActionPerformed
    
    private void resetForm() {
        txtCariPasien.setText("");
        panelInfoPasien.setVisible(false);
        panelStep2.setEnabled(false);
        btnDaftarkan.setEnabled(false);
        comboDokter.setSelectedIndex(0);
//        spinnerBiayaJasa.setValue(50000);
        this.selectedPasienId = null;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariPasien;
    private javax.swing.JButton btnDaftarkan;
    private javax.swing.JComboBox<String> comboDokter;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_dokter1;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_tgl_lahir;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelInfoPasien;
    private javax.swing.JPanel panelStep1;
    private javax.swing.JPanel panelStep2;
    private javax.swing.JTextField txtCariPasien;
    // End of variables declaration//GEN-END:variables


    private void cariPasien() {
        String keyword = txtCariPasien.getText().trim();

        // Validasi jika kosong
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi ID atau Nama Pasien terlebih dahulu!");
            return;
        }

        // Query: Cari berdasarkan ID ATAU Nama yang mirip
        String sql = "SELECT * FROM pasien WHERE pasien_id = ? OR nama_pasien LIKE ?";

        try (Connection conn = Database.KoneksiDatabase.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

             // Parameter 1: Cari ID Pasien (Persis)
             stmt.setString(1, keyword);
             // Parameter 2: Cari Nama (Mirip/Mengandung kata)
             stmt.setString(2, "%" + keyword + "%");

             ResultSet rs = stmt.executeQuery();
        
            if (rs.next()) {
                // --- JIKA DATA DITEMUKAN ---

                // 1. Simpan ID ke variabel global (untuk dipakai saat tombol Daftar diklik nanti)
                selectedPasienId = rs.getString("pasien_id");

                // 2. Tampilkan data ke Label GUI
                label_id.setText(rs.getString("pasien_id"));
                label_nama.setText(rs.getString("nama_pasien"));
                label_tgl_lahir.setText(rs.getString("tanggal_lahir"));
                label_alamat.setText(rs.getString("alamat"));

                // 3. Hitung Usia (Opsional tapi bagus)
                java.sql.Date tglLahir = rs.getDate("tanggal_lahir");
                if (tglLahir != null) {
                    // Konversi tanggal ke string + hitung tahun (logika sederhana)
                    String tglStr = new java.text.SimpleDateFormat("dd MMMM yyyy").format(tglLahir);
                    label_tgl_lahir.setText(tglStr);
                } else {
                    label_tgl_lahir.setText("-");
                }

                // Opsional: Beri warna hijau pada teks agar terlihat 'Found'
                label_nama.setForeground(new java.awt.Color(0, 153, 51));
                
                
                panelInfoPasien.setVisible(true); // Munculkan detail pasien
                panelStep2.setEnabled(true);      // Aktifkan panel dokter
                comboDokter.setEnabled(true);     // Aktifkan combo box
//                spinnerBiayaJasa.setEnabled(true);
                btnDaftarkan.setEnabled(true);    // Aktifkan tombol daftar
            // ==========================================

            } else {
                // --- JIKA DATA TIDAK DITEMUKAN ---
                resetFormPasien();
                JOptionPane.showMessageDialog(this, "Data pasien tidak ditemukan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
        }
    }

// Method helper untuk membersihkan label jika tidak ketemu
    private void resetFormPasien() {
        selectedPasienId = null; // Reset ID
        label_id.setText("-");
        label_nama.setText("-");
        label_tgl_lahir.setText("-");
        label_alamat.setText("-");
        label_nama.setForeground(java.awt.Color.BLACK); // Kembalikan warna hitam
    }
    
}
