/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;

import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author USER
 */
public final class JPanel_Informasi_Dokter extends javax.swing.JPanel {
    
    // Atribut
    Connection conn = KoneksiDatabase.getConnection();
    
    /**
     * Creates new form JPanel_Manajemen_Dokter
     */
    public JPanel_Informasi_Dokter() {
        initComponents();
        
        txtCari.putClientProperty("JTextField.placeholderText", "Cari dokter...");
        
        tblDokter.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12));
        tblDokter.getTableHeader().setOpaque(false);
        tblDokter.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblDokter.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih

        loadDataDokter(null);
    }
    
    
    private void loadDataDokter(String searchTerm) {
//       // 1. Siapkan Model Tabel
        DefaultTableModel model = (DefaultTableModel) tblDokter.getModel();
        model.setRowCount(0); // Bersihkan data lama
    
        // Set Header Kolom (Sesuai Gambar Desain Anda)
        String[] headers = {"ID Dokter", "Nama Lengkap", "Spesialisasi", "No. Telepon"};
        model.setColumnIdentifiers(headers);

        // 2. Siapkan Query (Gunakan JOIN)
        String sql = "SELECT d.dokter_id, u.nama_lengkap, d.spesialisasi, d.no_telepon " +
                     "FROM dokter d " +
                     "JOIN user u ON d.user_id = u.user_id "; // Gabungkan tabel user & dokter
    
        // Logika Pencarian
        if (searchTerm != null && !searchTerm.trim().isEmpty()) {
            sql += "WHERE u.nama_lengkap LIKE ? OR d.spesialisasi LIKE ? ";
        }
    
        sql += "ORDER BY u.nama_lengkap ASC"; // Urutkan berdasarkan nama

        // 3. Eksekusi Database
        
        try (PreparedStatement stmt = this.conn.prepareStatement(sql)) {

            // Isi parameter tanda tanya (?) jika ada pencarian
            if (searchTerm != null && !searchTerm.trim().isEmpty()) {
                String search = "%" + searchTerm + "%";
                stmt.setString(1, search);
                stmt.setString(2, search);
            }

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    // Ambil data gabungan dari user dan dokter
                    Object[] row = {
                        rs.getString("dokter_id"),      // Dari tabel dokter
                        rs.getString("nama_lengkap"),   // Dari tabel user
                        rs.getString("spesialisasi"),   // Dari tabel dokter
                        rs.getString("no_telepon")      // Dari tabel dokter
                    };
                    model.addRow(row);
                }
            }


        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data dokter: " + e.getMessage());
            e.printStackTrace();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKontrol = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Informasi Dokter Klinik");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelKontrol.setBackground(new java.awt.Color(255, 255, 255));

        btnCari.setBackground(new java.awt.Color(75, 167, 87));
        btnCari.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnCari.setForeground(new java.awt.Color(0, 0, 0));
        btnCari.setText("🔍");
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.setPreferredSize(new java.awt.Dimension(40, 40));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblDokter.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"D001", "dr. Abc", "Umum", "08123456781"},
                {"D002", "dr. Abcd, Sp.A", "Anak", "08123456782"},
                {"D003", "drg. Abcde", "Gigi", "08123456783"},
                {"D004", "dr. Abcdef, Sp.KK", "Kulit dan Kelamin", "08123456784"},
                {"D005", "dr. Abcdefg Sp.OG", "Kandungan dan Kebidanan", "08123456785"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama Lengkap", "Spesialisasi", "No. Telepon"
            }
        ));
        tblDokter.setGridColor(new java.awt.Color(224, 224, 224));
        tblDokter.setRowHeight(30);
        tblDokter.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblDokter.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblDokter.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblDokter);

        txtCari.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(0, 123, 255));
        btn_refresh.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("🔄 Refresh");
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(panelKontrol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(0, 575, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        // 1. Ambil kata kunci dari JTextField
        String searchTerm = txtCari.getText();

        // 2. Panggil method loadDataDokter dengan kata kunci tersebut
        loadDataDokter(searchTerm);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        loadDataDokter("");
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
