/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Resepsionis;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class JPanel_Dashboard_Resepsionis extends javax.swing.JPanel {
    
    private final ImageIcon patientIcon = new ImageIcon(getClass().getResource("/patient.png"));
    private final ImageIcon doctorIcon = new ImageIcon(getClass().getResource("/doctor.png"));
    private final ImageIcon calendarIcon = new ImageIcon(getClass().getResource("/calendar.png"));
    
    /**
     * Creates new form JPanel_Dashboard_Admin
     */
    public JPanel_Dashboard_Resepsionis() {
        initComponents();
        // Menjadwalkan update gambar setelah ukuran tombol tersedia
        SwingUtilities.invokeLater(() -> {
            // Sesuaikan ukuran gambar
            lblIconPasien.setIcon(new ImageIcon(patientIcon.getImage().getScaledInstance(lblIconPasien.getWidth(), lblIconPasien.getHeight(), Image.SCALE_SMOOTH)));
            lblIconDokter.setIcon(new ImageIcon(doctorIcon.getImage().getScaledInstance(lblIconDokter.getWidth(), lblIconDokter.getHeight(), Image.SCALE_SMOOTH)));
            lblIconKunjungan.setIcon(new ImageIcon(calendarIcon.getImage().getScaledInstance(lblIconKunjungan.getWidth(), lblIconKunjungan.getHeight(), Image.SCALE_SMOOTH)));
        });
        loadDashboardData();
    }
    
    public void loadDashboardData() {
        // Contoh (angka_dari_db harus berupa String)
//        lblJumlahPasien.setText(angka_dari_db_pasien);
//        lblJumlahDokter.setText(angka_dari_db_dokter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardTotalPasien = new javax.swing.JPanel();
        lblIconPasien = new javax.swing.JLabel();
        lblJumlahPasien = new javax.swing.JLabel();
        lblTitlePasien = new javax.swing.JLabel();
        cardDokterAktif = new javax.swing.JPanel();
        lblIconDokter = new javax.swing.JLabel();
        lblJumlahDokter = new javax.swing.JLabel();
        lblTitleDokter = new javax.swing.JLabel();
        cardKunjunganHariIni = new javax.swing.JPanel();
        lblIconKunjungan = new javax.swing.JLabel();
        lblJumlahKunjungan = new javax.swing.JLabel();
        lblTitleKunjungan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAksesTambahPasien = new javax.swing.JButton();
        btnAksesLihatJadwal = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Dashboard");

        lblWelcome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 153, 153));
        lblWelcome.setText("Selamat datang kembali, [Nama Admin]! Ini adalah ringkasan klinik Anda hari ini.");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        cardTotalPasien.setBackground(new java.awt.Color(255, 255, 255));
        cardTotalPasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(50, 120, 220)));
        cardTotalPasien.setPreferredSize(new java.awt.Dimension(250, 120));

        lblIconPasien.setBackground(java.awt.Color.white);
        lblIconPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patient.png"))); // NOI18N

        lblJumlahPasien.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblJumlahPasien.setText("1.420");

        lblTitlePasien.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTitlePasien.setForeground(new java.awt.Color(102, 102, 102));
        lblTitlePasien.setText("Total Pasien Terdaftar");

        javax.swing.GroupLayout cardTotalPasienLayout = new javax.swing.GroupLayout(cardTotalPasien);
        cardTotalPasien.setLayout(cardTotalPasienLayout);
        cardTotalPasienLayout.setHorizontalGroup(
            cardTotalPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTotalPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardTotalPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahPasien)
                    .addComponent(lblTitlePasien))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        cardTotalPasienLayout.setVerticalGroup(
            cardTotalPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTotalPasienLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cardTotalPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardTotalPasienLayout.createSequentialGroup()
                        .addComponent(lblJumlahPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitlePasien)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        cardDokterAktif.setBackground(new java.awt.Color(255, 255, 255));
        cardDokterAktif.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(25, 135, 84)));
        cardDokterAktif.setPreferredSize(new java.awt.Dimension(250, 120));

        lblIconDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor.png"))); // NOI18N

        lblJumlahDokter.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblJumlahDokter.setText("12");

        lblTitleDokter.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTitleDokter.setForeground(new java.awt.Color(102, 102, 102));
        lblTitleDokter.setText("Dokter Aktif");

        javax.swing.GroupLayout cardDokterAktifLayout = new javax.swing.GroupLayout(cardDokterAktif);
        cardDokterAktif.setLayout(cardDokterAktifLayout);
        cardDokterAktifLayout.setHorizontalGroup(
            cardDokterAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDokterAktifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardDokterAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahDokter)
                    .addComponent(lblTitleDokter))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        cardDokterAktifLayout.setVerticalGroup(
            cardDokterAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDokterAktifLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(cardDokterAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardDokterAktifLayout.createSequentialGroup()
                        .addComponent(lblJumlahDokter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleDokter)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        cardKunjunganHariIni.setBackground(new java.awt.Color(255, 255, 255));
        cardKunjunganHariIni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(255, 193, 7)));
        cardKunjunganHariIni.setPreferredSize(new java.awt.Dimension(250, 120));

        lblIconKunjungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N

        lblJumlahKunjungan.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblJumlahKunjungan.setText("35");

        lblTitleKunjungan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTitleKunjungan.setForeground(new java.awt.Color(102, 102, 102));
        lblTitleKunjungan.setText("Kunjungan Hari ini");

        javax.swing.GroupLayout cardKunjunganHariIniLayout = new javax.swing.GroupLayout(cardKunjunganHariIni);
        cardKunjunganHariIni.setLayout(cardKunjunganHariIniLayout);
        cardKunjunganHariIniLayout.setHorizontalGroup(
            cardKunjunganHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardKunjunganHariIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardKunjunganHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahKunjungan)
                    .addComponent(lblTitleKunjungan))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        cardKunjunganHariIniLayout.setVerticalGroup(
            cardKunjunganHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardKunjunganHariIniLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cardKunjunganHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardKunjunganHariIniLayout.createSequentialGroup()
                        .addComponent(lblJumlahKunjungan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleKunjungan)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Akses Cepat");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnAksesTambahPasien.setBackground(new java.awt.Color(50, 120, 220));
        btnAksesTambahPasien.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAksesTambahPasien.setForeground(new java.awt.Color(255, 255, 255));
        btnAksesTambahPasien.setText("➕  Registrasi Pasien Baru");
        btnAksesTambahPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAksesTambahPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksesTambahPasienActionPerformed(evt);
            }
        });

        btnAksesLihatJadwal.setBackground(new java.awt.Color(25, 135, 84));
        btnAksesLihatJadwal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAksesLihatJadwal.setForeground(new java.awt.Color(255, 255, 255));
        btnAksesLihatJadwal.setText("📅  Lihat Jadwal Dokter");
        btnAksesLihatJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAksesLihatJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksesLihatJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcome)
                    .addComponent(lblJudul)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAksesTambahPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAksesLihatJadwal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardTotalPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardDokterAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardKunjunganHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJudul)
                .addGap(12, 12, 12)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardTotalPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardDokterAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardKunjunganHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAksesTambahPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksesLihatJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAksesTambahPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksesTambahPasienActionPerformed
        // TODO add your handling code here:
        Container parent = this.getParent();

        // 2. Dapatkan CardLayout dari panelContent
        CardLayout cl = (CardLayout) parent.getLayout();

        // 3. Panggil kartu "cardPasien"
        cl.show(parent, "cardPasien");
    }//GEN-LAST:event_btnAksesTambahPasienActionPerformed

    private void btnAksesLihatJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksesLihatJadwalActionPerformed
        // TODO add your handling code here:
        Container parent = this.getParent();

        // 2. Dapatkan CardLayout dari panelContent
        CardLayout cl = (CardLayout) parent.getLayout();

        // 3. Panggil kartu "cardJadwal"
        cl.show(parent, "cardJadwal");
    }//GEN-LAST:event_btnAksesLihatJadwalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksesLihatJadwal;
    private javax.swing.JButton btnAksesTambahPasien;
    private javax.swing.JPanel cardDokterAktif;
    private javax.swing.JPanel cardKunjunganHariIni;
    private javax.swing.JPanel cardTotalPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIconDokter;
    private javax.swing.JLabel lblIconKunjungan;
    private javax.swing.JLabel lblIconPasien;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlahDokter;
    private javax.swing.JLabel lblJumlahKunjungan;
    private javax.swing.JLabel lblJumlahPasien;
    private javax.swing.JLabel lblTitleDokter;
    private javax.swing.JLabel lblTitleKunjungan;
    private javax.swing.JLabel lblTitlePasien;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
