/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Kasir;

import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.logging.Level; // Tambahkan ini (jika belum ada)
import java.util.logging.Logger; // Tambahkan ini

public class JDialog_Pembayaran extends javax.swing.JDialog {
    
    private String idPembayaran;
    private double totalTagihanVal = 0;
    private static final Logger logger = Logger.getLogger(JDialog_Pembayaran.class.getName()); // <-- TAMBAHKAN INI


    // Konstruktor Utama (Menerima ID)
    public JDialog_Pembayaran(java.awt.Frame parent, boolean modal, String idPembayaran) {
    super(parent, modal);
    this.idPembayaran = idPembayaran;
    initComponents();
    this.setLocationRelativeTo(null); // Biar muncul di tengah layar
    
    loadDataPembayaran();    // Ambil data tagihan
    initHitungKembalian();   // Aktifkan hitung otomatis
}
    // Konstruktor Default (Biar desain tidak error)
    public JDialog_Pembayaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void loadDataPembayaran() {
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        KoneksiDatabase db = new KoneksiDatabase();
        conn = db.getConnection();

        String sql =
            "SELECT k.kunjungan_id, pas.nama_pasien, " +
            "SUM(dl.biaya_saat_ini) AS total_bayar " +
            "FROM kunjungan k " +
            "JOIN pasien pas ON k.pasien_id = pas.pasien_id " +
            "LEFT JOIN detail_layanan dl ON k.kunjungan_id = dl.kunjungan_id " +
            "WHERE k.kunjungan_id = ? " +
            "GROUP BY k.kunjungan_id";

        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, idPembayaran);
        rs = pstmt.executeQuery();

        if (rs.next()) {
            lblNamaPasien.setText(rs.getString("nama_pasien"));
            totalTagihanVal = rs.getDouble("total_bayar");
            txtTotalTagihan.setText(
                String.format("Rp %,.2f", totalTagihanVal)
            );
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Data Kunjungan ID: " + idPembayaran + " Tidak Ditemukan!"
            );
            dispose();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Gagal menutup koneksi", e);
        }
    }
}

    // Logika Hitung Kembalian Otomatis
    private void initHitungKembalian() {
        txtBayar.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) { hitung(); }
            public void removeUpdate(DocumentEvent e) { hitung(); }
            public void insertUpdate(DocumentEvent e) { hitung(); }

            public void hitung() {
                try {
                    String input = txtBayar.getText().replace(",", ""); // Hapus koma jika ada
                    double bayar = Double.parseDouble(input);
                    double kembali = bayar - totalTagihanVal;
                    
                    lblKembalian.setText(String.format("Rp %,.2f", kembali));
                    
                    // Tombol bayar hanya aktif jika uang cukup
                    btnKonfirmasiBayar.setEnabled(kembali >= 0);
                } catch (NumberFormatException ex) {
                    lblKembalian.setText("Rp 0");
                    btnKonfirmasiBayar.setEnabled(false);
                }
            }
        });
    }

    // Method untuk Tombol "BAYAR"
    // Hubungkan lewat Events -> Action -> actionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        JLabel = new javax.swing.JLabel();
        lblNamaPasien = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalTagihan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbMetodeBayar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        btnKonfirmasiBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelUtama.setLayout(new java.awt.BorderLayout(20, 20));

        jLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Pembayaran Tagihan");
        panelUtama.add(jLabelHeader, java.awt.BorderLayout.PAGE_START);

        jPanelForm.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        JLabel.setText("Nama Pasien");
        jPanelForm.add(JLabel);

        lblNamaPasien.setText("-");
        jPanelForm.add(lblNamaPasien);

        jLabel2.setText("Total Tagihan");
        jPanelForm.add(jLabel2);

        txtTotalTagihan.setEditable(false);
        txtTotalTagihan.setText("0");
        txtTotalTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalTagihanActionPerformed(evt);
            }
        });
        jPanelForm.add(txtTotalTagihan);

        jLabel10.setText("Metode Bayar");
        jPanelForm.add(jLabel10);

        cmbMetodeBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit", "Tunai", "Asuransi" }));
        cmbMetodeBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodeBayarActionPerformed(evt);
            }
        });
        jPanelForm.add(cmbMetodeBayar);

        jLabel9.setText("Jumlah Bayar");
        jPanelForm.add(jLabel9);

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });
        jPanelForm.add(txtBayar);

        jLabel8.setText("Kembalian");
        jPanelForm.add(jLabel8);

        lblKembalian.setText("0");
        jPanelForm.add(lblKembalian);

        panelUtama.add(jPanelForm, java.awt.BorderLayout.CENTER);

        btnKonfirmasiBayar.setText("KONFIRMASI BAYAR");
        btnKonfirmasiBayar.setEnabled(false);
        btnKonfirmasiBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiBayarActionPerformed(evt);
            }
        });
        jPanelButton.add(btnKonfirmasiBayar);

        panelUtama.add(jPanelButton, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalTagihanActionPerformed

    private void btnKonfirmasiBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiBayarActionPerformed
     Connection conn = null;
    PreparedStatement pstmtCek = null;
    PreparedStatement pstmtInsert = null;
    PreparedStatement pstmtUpdateStatus = null;
    ResultSet rsCek = null;

    try {
    KoneksiDatabase db = new KoneksiDatabase();
    conn = db.getConnection();
    conn.setAutoCommit(false); // Memulai transaksi agar data sinkron

    // 1. CEK apakah kunjungan_id ini sudah pernah dibayar
    String sqlCek = "SELECT COUNT(*) FROM pembayaran WHERE kunjungan_id = ?";
    pstmtCek = conn.prepareStatement(sqlCek);
    pstmtCek.setString(1, idPembayaran);
    rsCek = pstmtCek.executeQuery();
    
    if (rsCek.next() && rsCek.getInt(1) > 0) {
        JOptionPane.showMessageDialog(this, "Transaksi ini sudah lunas sebelumnya!");
        this.dispose();
        return;
    }

    // 2. INSERT ke tabel pembayaran
    String sqlInsert = "INSERT INTO pembayaran (kunjungan_id, tanggal_bayar, metode_bayar, " +
                       "total_biaya_jasa, total_biaya_obat, total_bayar, user_kasir_id) " +
                       "VALUES (?, NOW(), ?, ?, ?, ?, ?)";
    
    pstmtInsert = conn.prepareStatement(sqlInsert);
    pstmtInsert.setString(1, idPembayaran);
    pstmtInsert.setString(2, cmbMetodeBayar.getSelectedItem().toString());
    pstmtInsert.setDouble(3, totalTagihanVal); 
    pstmtInsert.setDouble(4, 0.0); 
    pstmtInsert.setDouble(5, totalTagihanVal); 
    pstmtInsert.setInt(6, 1); 
    pstmtInsert.executeUpdate();

    // 3. UPDATE status menjadi 'Lunas' (Pastikan ejaan 'Lunas' sama dengan di DB)
    String sqlUpdateStatus = "UPDATE kunjungan SET status_kunjungan = 'Lunas' WHERE kunjungan_id = ?";
    pstmtUpdateStatus = conn.prepareStatement(sqlUpdateStatus);
    pstmtUpdateStatus.setString(1, idPembayaran);
    
    int rowsAffected = pstmtUpdateStatus.executeUpdate();

    if (rowsAffected > 0) {
        conn.commit(); // Simpan permanen ke database
        JOptionPane.showMessageDialog(this, "Pembayaran Berhasil! Status sekarang LUNAS.");
        this.dispose();
    } else {
        conn.rollback(); // Batalkan jika update gagal
        JOptionPane.showMessageDialog(this, "Gagal mengupdate status kunjungan.");
    }

} catch (Exception e) {
    if (conn != null) try { conn.rollback(); } catch (Exception ex) {}
    JOptionPane.showMessageDialog(this, "Gagal Bayar: " + e.getMessage());
    e.printStackTrace();
}
finally {
        // Tutup semua resource
        try {
            if (rsCek != null) rsCek.close();
            if (pstmtCek != null) pstmtCek.close();
            if (pstmtInsert != null) pstmtInsert.close();
            if (pstmtUpdateStatus != null) pstmtUpdateStatus.close();
            if (conn != null) conn.close();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Gagal menutup koneksi", ex);
        }
    }

    }//GEN-LAST:event_btnKonfirmasiBayarActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void cmbMetodeBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodeBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodeBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialog_Pembayaran dialog = new JDialog_Pembayaran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JButton btnKonfirmasiBayar;
    private javax.swing.JComboBox<String> cmbMetodeBayar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblNamaPasien;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtTotalTagihan;
    // End of variables declaration//GEN-END:variables
}
