
package Kasir;

import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JPanel_Riwayat_Transaksi extends javax.swing.JPanel {

    public JPanel_Riwayat_Transaksi() {
        initComponents();
        tampilkanRiwayat(); 
    }

    public final void tampilkanRiwayat() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Transaksi");
    model.addColumn("Tanggal Bayar");
    model.addColumn("Nama Pasien");
    model.addColumn("Metode");
    model.addColumn("Total Bayar");

    // Ambil input dari textfield
    String tglMulai = jTextField1.getText();
    String tglSelesai = jTextField2.getText();

    try {
        try (Connection conn = KoneksiDatabase.getConnection()) {
            String sql;
            // Logika: Jika textfield masih berisi teks default, tampilkan semua data.
            // Jika sudah diisi tanggal, gunakan filter BETWEEN.
            if (tglMulai.equals("Tanggal Mulai") || tglSelesai.equals("Tanggal Selesai")) {
                sql = "SELECT p.pembayaran_id, p.tanggal_bayar, pas.nama_pasien, p.metode_bayar, p.total_bayar " +
                        "FROM pembayaran p " +
                        "JOIN kunjungan k ON p.kunjungan_id = k.kunjungan_id " +
                        "JOIN pasien pas ON k.pasien_id = pas.pasien_id " +
                        "ORDER BY p.tanggal_bayar DESC";
            } else {
                sql = "SELECT p.pembayaran_id, p.tanggal_bayar, pas.nama_pasien, p.metode_bayar, p.total_bayar " +
                        "FROM pembayaran p " +
                        "JOIN kunjungan k ON p.kunjungan_id = k.kunjungan_id " +
                        "JOIN pasien pas ON k.pasien_id = pas.pasien_id " +
                        "WHERE p.tanggal_bayar BETWEEN '" + tglMulai + "' AND '" + tglSelesai + "' " +
                        "ORDER BY p.tanggal_bayar DESC";
            }
            
            try (Statement stat = conn.createStatement(); ResultSet res = stat.executeQuery(sql)) {
                
                while (res.next()) {
                    model.addRow(new Object[]{
                        res.getString("pembayaran_id"),   // Gunakan nama kolom saja, tanpa p.
                        res.getString("tanggal_bayar"),
                        res.getString("nama_pasien"),
                        res.getString("metode_bayar"),
                        res.getString("total_bayar")
                    });
                }
                tblRiwayatTransaksi.setModel(model);
                
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}
    
    // Tombol Refresh/Filter
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeaderFilter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayatTransaksi = new javax.swing.JTable();
        PanelAksi = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Riwayat Transaksi Selesai");
        panelHeaderFilter.add(jLabel1);

        jLabel2.setText("Dari");
        panelHeaderFilter.add(jLabel2);

        jTextField1.setText("Tanggal Mulai");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelHeaderFilter.add(jTextField1);

        jLabel3.setText("Sampai");
        panelHeaderFilter.add(jLabel3);

        jTextField2.setText("Tanggal Selesai");
        panelHeaderFilter.add(jTextField2);

        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelHeaderFilter.add(jButton1);

        add(panelHeaderFilter, java.awt.BorderLayout.PAGE_START);

        tblRiwayatTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayatTransaksi);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelAksi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        add(PanelAksi, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.getText().equals("Tanggal Mulai") || jTextField2.getText().equals("")) {
         JOptionPane.showMessageDialog(this, "Masukkan format tanggal YYYY-MM-DD (Contoh: 2025-01-01)");
    } else {
         tampilkanRiwayat();
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panelHeaderFilter;
    private javax.swing.JTable tblRiwayatTransaksi;
    // End of variables declaration//GEN-END:variables
}
