/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Apoteker.JFrameMainApoteker;
import Resepsionis.JFrame_Main_Resepsionis;
import Dokter.JFrame_Main_Dokter;
import Kasir.JFrame_Main_Kasir;
import Manajemen.JFrame_Main_Manajemen;
//import Resepsionis.JPanel_Dashboard_Resepsionis;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import at.favre.lib.crypto.bcrypt.BCrypt;


/**
 *
 * @author USER
 */
public class JFrame_Login extends javax.swing.JFrame {
    
    Connection conn;
    KoneksiDatabase koneksi;
//    Statement stmt;
//    ResultSet rs;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Login.class.getName());
    
    private boolean isPasswordVisible = false;
    // Ikon klinik
    private final ImageIcon clinicIcon = new ImageIcon(getClass().getResource("/gambarKlinik.png"));
    // Ikon tombol show/hide (mata terbuka)
    private final ImageIcon eyeOpenIcon = new ImageIcon(getClass().getResource("/eye.png"));
    // Ikon tombol show/hide (mata tertutup)
    private final ImageIcon eyeClosedIcon = new ImageIcon(getClass().getResource("/eyeslash.png")); 
    
    /**
     * Creates new form JFrame_Login
     */
    public JFrame_Login() {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        koneksi = new KoneksiDatabase();
        try {
            conn = koneksi.getConnection();
            if (conn != null) {
//                JOptionPane.showMessageDialog(this, "Koneksi ke Database Berhasil, Silahkan Login!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat koneksi: " + e.getMessage());
        }
        // Menambahkan placeholder text secara manual
        txt_username.putClientProperty("JTextField.placeholderText", "Masukkan username...");
        txt_password.putClientProperty("JTextField.placeholderText", "Masukkan password...");
        
        // Menjadwalkan update gambar setelah ukuran tombol tersedia
        SwingUtilities.invokeLater(() -> {
            // Sesuaikan ukuran gambar
            labelIconKlinik.setIcon(new ImageIcon(clinicIcon.getImage().getScaledInstance(labelIconKlinik.getWidth(), labelIconKlinik.getHeight(), Image.SCALE_SMOOTH)));
            
            showHidePasswordButton.setIcon(new ImageIcon(eyeClosedIcon.getImage().getScaledInstance(showHidePasswordButton.getWidth(), showHidePasswordButton.getHeight(), Image.SCALE_SMOOTH)));
            
        });
    }
    
    private void notifikasiLoginGagal() {
        JOptionPane.showMessageDialog(this, 
                    "Username atau Password salah!",
                    "Login Gagal",
                    JOptionPane.ERROR_MESSAGE);
    } 
    
    // Username dan Password Login Sementara
//    private final String usernameResepsionis = "resepsionis";
//    private final String passwordResepsionis = "resepsionis";
//        
//    private final String usernameDokter = "dokter";
//    private final String passwordDokter = "dokter";
//        
//    private final String usernameApoteker = "apoteker";
//    private final String passwordApoteker = "apoteker";
//        
//    private final String usernameKasir = "kasir";
//    private final String passwordKasir = "kasir";
//        
//    private final String usernameManajemen = "manajemen";
//    private final String passwordManajemen = "manajemen";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_kiri = new javax.swing.JPanel();
        labelIconKlinik = new javax.swing.JLabel();
        panel_kanan = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        showHidePasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Klinik Sehat Selalu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panel_kiri.setBackground(new java.awt.Color(180, 220, 240));

        labelIconKlinik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarKlinik.png"))); // NOI18N

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kiriLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(labelIconKlinik)
                .addGap(59, 59, 59))
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(labelIconKlinik)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        panel_kanan.setBackground(new java.awt.Color(255, 255, 255));
        panel_kanan.setPreferredSize(new java.awt.Dimension(200, 75));

        label_title.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        label_title.setForeground(java.awt.Color.black);
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("Klinik Sehat Selalu");

        label_username.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        label_username.setForeground(java.awt.Color.black);
        label_username.setText("Username");

        txt_username.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        label_password.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        label_password.setForeground(java.awt.Color.black);
        label_password.setText("Password");

        txt_password.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(50, 120, 220));
        btn_login.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_login.setForeground(java.awt.Color.white);
        btn_login.setText("➜]  Login");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        showHidePasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eyeslash.png"))); // NOI18N
        showHidePasswordButton.setContentAreaFilled(false);
        showHidePasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showHidePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHidePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_kananLayout = new javax.swing.GroupLayout(panel_kanan);
        panel_kanan.setLayout(panel_kananLayout);
        panel_kananLayout.setHorizontalGroup(
            panel_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_kananLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_password)
                    .addComponent(label_username)
                    .addComponent(txt_password)
                    .addComponent(txt_username)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHidePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panel_kananLayout.setVerticalGroup(
            panel_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kananLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_title)
                .addGap(40, 40, 40)
                .addComponent(label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kananLayout.createSequentialGroup()
                        .addComponent(showHidePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(48, 48, 48)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_kiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_kanan, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_kiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_kanan, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed
    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = txt_username.getText();
        String password = new String(txt_password.getPassword());

        // Query: hanya cari berdasarkan username
        String sql = "SELECT Username, password, role FROM user WHERE Username=?";

        try {
            // Prepare dan eksekusi query ke DB
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            ResultSet result = pst.executeQuery();

            if (result.next()) {
                // Ambil hash password dari DB
                String hashedPassword = result.getString("password");
                
                // Verifikasi password (bcrypt Favre)
                BCrypt.Result verify = BCrypt.verifyer().verify(password.toCharArray(), hashedPassword);
                
                if (verify.verified) {
                    
                    // Ambil role dari database
                    String role = result.getString("role"); 

                    JOptionPane.showMessageDialog(this, "Login Berhasil sebagai " + role);
                    
                    dispose();  // Tutup form login

                    //  ROLE-BASED NAVIGATION
                    switch (role.toLowerCase()) {
                        case "resepsionis" -> {
                            JFrame_Main_Resepsionis tampil = new JFrame_Main_Resepsionis();
                          tampil.setVisible(true);
                        }
                        case "dokter" -> {
                            JFrame_Main_Dokter tampil1 = new JFrame_Main_Dokter();
                            tampil1.setVisible(true);
                        }
                        case "apoteker" -> {
                            JFrameMainApoteker tampil2 = new JFrameMainApoteker();
                            tampil2.setVisible(true);
                        }
                        case "kasir" -> {
                            new JFrame_Main_Kasir().setVisible(true);
                        }
                        case "manajemen" -> {
                            JFrame_Main_Manajemen tampil3 = new JFrame_Main_Manajemen();
                            tampil3.setVisible(true);
                        }
                        default -> {
                            JOptionPane.showMessageDialog(this, 
                                "Role tidak dikenal: " + role, 
                                "Error", 
                                JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } else {
                    this.notifikasiLoginGagal();
                }

            } else {
                this.notifikasiLoginGagal();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
 

    //kode berhasil login sederhana    
//    String username = txt_username.getText();
//    String pass = new String(txt_passw   ord.getPassword());
//
//    String sql = "SELECT Username, role FROM users WHERE username=? AND password=?\";";
//
//    try {
//        PreparedStatement pst = conn.prepareStatement(sql);
//        pst.setString(1, username);
//        pst.setString(2, pass);
//        ResultSet result = pst.executeQuery();
//
//    if (result.next()) {
//        // Login berhasil
//        JOptionPane.showMessageDialog(null, "Login Berhasil");
//
//        dispose();
//        
//        JFrame_Main_Resepsionis tampil = new JFrame_Main_Resepsionis();
//        tampil.setVisible(true);
//    } else {
//        // Login gagal
//        JOptionPane.showMessageDialog(null, "Username atau Password salah");
//    }
//
//    } catch (SQLException e) {
//    JOptionPane.showMessageDialog(null, e.getMessage());
//    }
//
//        
        
        
        
       //kode logika youtube 
//        String username = txt_username.getText();
//        String password = txt_password.getPassword();
//        
//        String sql = "SELECT * FROM user WHERE Username = '" + username + "' AND password = '" + String.valueOf(password) + "'";
//        try{
//            stmt = conn.createStatement();
//            rs = stmt.executeQuery(sql);
//            
//            
//            JOptionPane.showMessageDialog(rootPane, "Welcome " + rs.getString("Username") + "!");
//            while (rs.next()){
//                
//                dispose();
//                
//                JPanel_Dashboard_Resepsionis tampil = new JPanel_Dashboard_Resepsionis();
//                tampil.setVisible(true);
//            }
//            
//        }
//        catch (SQLException e){
//            JOptionPane.showMessageDialog(rootPane, e);
//        }   

// TODO add your handling code here:
//        String username = txt_username.getText();
//        String password = new String(txt_password.getPassword());
//        
//        // --- INI LOGIKA VALIDASI ANDA ---
//        switch (username) { 
//            // Login Resepsionis
//            case usernameResepsionis -> {
//                // Logika login Resepsionis
//                if (password.equals(passwordResepsionis)) {
//                    // Jika login berhasil untuk Resepsionis
//                    JFrame_Main_Resepsionis dashboardResepsionis = new JFrame_Main_Resepsionis();
//                    dashboardResepsionis.setVisible(true);
//                    this.dispose();
//                } else {
//                    notifikasiLoginGagal();
//                }
//            }
//
//            case usernameDokter -> {
//                // Login Dokter
//                if (password.equals(passwordDokter)) {
//                    // Jika login berhasil untuk Dokter
//                    String idDokterDb = "D001"; 
//                    String namaDokterDb = "Tirta";
//                    String spesialisasiDb = "Umum";
//                    JFrame_Main_Dokter dashboardDokter = new JFrame_Main_Dokter(idDokterDb, namaDokterDb, spesialisasiDb);
//                    dashboardDokter.setVisible(true);
//                    this.dispose();
//                } else {
//                    notifikasiLoginGagal();
//                }
//            }
//
//            case usernameApoteker -> {
//                // Login Apoteker
//                if (password.equals(passwordApoteker)) {
//                    // Jika login berhasil untuk Apoteker
//                    JFrameMainApoteker dashboardApoteker = new JFrameMainApoteker();
//                    dashboardApoteker.setVisible(true);
//                    this.dispose();
//                } else {
//                    notifikasiLoginGagal();
//                }
//            }
//
//            case usernameKasir -> {
//                // Login Kasir
//                if (password.equals(passwordKasir)) {
//                    // Jika login berhasil untuk Kasir
//                    JFrame_Main_Kasir dashboardKasir = new JFrame_Main_Kasir();
//                    dashboardKasir.setVisible(true);
//                    this.dispose();
//                } else {
//                    notifikasiLoginGagal();
//                }
//            }
//
//            case usernameManajemen -> {
//                // Login Manajemen atau Superadmin
//                if (password.equals(passwordManajemen)) {
//                    // Jika login berhasil untuk Superadmin
//                    JFrame_Main_Manajemen dashboardManajemen = new JFrame_Main_Manajemen();
//                    dashboardManajemen.setVisible(true);
//                    this.dispose();
//                } else {
//                    notifikasiLoginGagal();
//                }
//            }
//
//            default -> {
//                notifikasiLoginGagal();
//            }
//        }
    }//GEN-LAST:event_btn_loginActionPerformed
    
 
    private void showHidePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHidePasswordButtonActionPerformed
        Image eyeOpenIconResized = eyeOpenIcon.getImage().getScaledInstance(showHidePasswordButton.getWidth(), showHidePasswordButton.getHeight(), Image.SCALE_SMOOTH);
        Image eyeClosedIconResized = eyeClosedIcon.getImage().getScaledInstance(showHidePasswordButton.getWidth(), showHidePasswordButton.getHeight(), Image.SCALE_SMOOTH);
        if (isPasswordVisible) {
            // Jika password sedang ditampilkan, sembunyikan password
            txt_password.setEchoChar('*');  // Sembunyikan password dengan karakter '*'
            showHidePasswordButton.setIcon(new ImageIcon(eyeClosedIconResized)); // Ganti ikon ke mata tertutup
        } else {
            // Jika password tidak ditampilkan, tampilkan password
            txt_password.setEchoChar((char) 0);  // Tampilkan password dengan echoChar 0
            showHidePasswordButton.setIcon(new ImageIcon(eyeOpenIconResized)); // Ganti ikon ke mata terbuka
        }

        // Toggle status visibility password
        isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_showHidePasswordButtonActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
        // Cek apakah tombol yang ditekan adalah ENTER (VK_ENTER)
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {

            // Panggil fungsi yang sama dengan yang dipicu oleh klik tombol Login
            // Kita perlu membuat objek ActionEvent tiruan atau memanggil fungsi inti.
            // Cara terbaik adalah memanggil fungsi ActionPerformed dengan null atau membuat ActionEvent baru.
            btn_loginActionPerformed(null); 
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel labelIconKlinik;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel panel_kanan;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JButton showHidePasswordButton;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
