/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kasir;
import com.formdev.flatlaf.FlatLightLaf;
/**
 *
 * @author karuna
 */
public class JFrame_Main_Kasir extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Main_Kasir.class.getName());
    
    // Deklarasi panel konten baru
    private JPanel_Antrean_Pembayaran panelAntreanPembayaran; 
    private JPanel_Riwayat_Transaksi panelRiwayatTransaksi;
    /**
     * Creates new form JFrame_MainKasir
     */
    public JFrame_Main_Kasir() {
        initComponents();
        
        // Inisialisasi panel konten
        panelAntreanPembayaran = new JPanel_Antrean_Pembayaran(); 
        panelRiwayatTransaksi = new JPanel_Riwayat_Transaksi();
        // Tambahkan panel ke PanelKonten dengan nama tertentu untuk CardLayout
        PanelKonten.add(panelAntreanPembayaran, "ANTREAN_PEMBAYARAN"); 
        PanelKonten.add(panelRiwayatTransaksi, "RIWAYAT_TRANSAKSI");
        // Panggil method untuk mengatur aksi tombol
        setupListeners();
        
        // Tampilkan panel antrean pembayaran sebagai panel default saat aplikasi dimulai
        showPanel("ANTREAN_PEMBAYARAN");
    }
    
    private void setupListeners() {
        btnAntreanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntreanPembayaranActionPerformed(evt);
            }
        });
        
        // Listener untuk tombol Riwayat Transaksi (jika Anda memiliki panelnya)
        btnRiwayatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatTransaksiActionPerformed(evt);
            }
        });
    }

    // Method baru untuk menampilkan panel berdasarkan nama CardLayout
    private void showPanel(String panelName) {
        java.awt.CardLayout cl = (java.awt.CardLayout)(PanelKonten.getLayout());
        cl.show(PanelKonten, panelName);
    }
    
    // ... (rest of the class)
    
    // Tambahkan method action listener yang baru
    private void btnAntreanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        panelAntreanPembayaran.tampilkanAntrean(); // <--- TAMBAHAN: Memanggil method refresh data
        showPanel("ANTREAN_PEMBAYARAN"); // Tampilkan panel antrean pembayaran
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAntreanPembayaran = new javax.swing.JButton();
        btnRiwayatTransaksi = new javax.swing.JButton();
        PanelKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Kasir");

        btnAntreanPembayaran.setText("Antrean Pembayaran");

        btnRiwayatTransaksi.setText("Riwayat Transaksi");
        btnRiwayatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addComponent(btnAntreanPembayaran)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnRiwayatTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAntreanPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRiwayatTransaksi)
                .addGap(0, 220, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        PanelKonten.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelKonten, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRiwayatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatTransaksiActionPerformed
   panelRiwayatTransaksi.tampilkanRiwayat(); // <--- TAMBAHAN: Memanggil method refresh data
        showPanel("RIWAYAT_TRANSAKSI");
    }//GEN-LAST:event_btnRiwayatTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            FlatLightLaf.setup(); 
  
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to initialize FlatLaf", ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Main_Kasir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelKonten;
    private javax.swing.JButton btnAntreanPembayaran;
    private javax.swing.JButton btnRiwayatTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
