/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manajemen;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kusuma
 */
public class JPanel_Laporan extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Laporan
     */
    public JPanel_Laporan() {
        initComponents();
        initTampilanAwal();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_PilihLaporan = new javax.swing.JLabel();
        comboJenisLaporan = new javax.swing.JComboBox<>();
        taggal_dari = new com.toedter.calendar.JDateChooser();
        tanggal_sampai = new com.toedter.calendar.JDateChooser();
        lbl_dariTanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTampilkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        lblTotalPendapatan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbl_PilihLaporan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbl_PilihLaporan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_PilihLaporan.setText("Pilih Laporan");

        comboJenisLaporan.setBackground(new java.awt.Color(0, 0, 204));
        comboJenisLaporan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comboJenisLaporan.setForeground(new java.awt.Color(255, 255, 255));
        comboJenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Pendapatan", "Laporan Kunjungan Pasien", "Laporan Penggunaan Obat", " " }));
        comboJenisLaporan.setOpaque(true);
        comboJenisLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisLaporanActionPerformed(evt);
            }
        });

        taggal_dari.setBackground(new java.awt.Color(255, 255, 255));
        taggal_dari.setForeground(new java.awt.Color(0, 0, 0));

        tanggal_sampai.setBackground(new java.awt.Color(255, 255, 255));
        tanggal_sampai.setForeground(new java.awt.Color(0, 0, 0));

        lbl_dariTanggal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_dariTanggal.setForeground(new java.awt.Color(0, 0, 0));
        lbl_dariTanggal.setText("Dari Tanggal");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sampai Tanggal");

        btnTampilkan.setBackground(new java.awt.Color(0, 0, 153));
        btnTampilkan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnTampilkan.setForeground(new java.awt.Color(255, 255, 255));
        btnTampilkan.setText("Tampilkan Laporan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLaporan.setSelectionBackground(new java.awt.Color(51, 102, 255));
        tblLaporan.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblLaporan);

        lblTotalPendapatan.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lblTotalPendapatan.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalPendapatan.setText("Total Pendapatan: Rp. 120.000.000");

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Export");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalPendapatan)
                                .addGap(138, 138, 138)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_PilihLaporan)
                        .addGap(18, 18, 18)
                        .addComponent(comboJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taggal_dari, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dariTanggal)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tanggal_sampai, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(btnTampilkan))
                            .addComponent(jLabel1))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dariTanggal)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(taggal_dari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_PilihLaporan)
                        .addComponent(comboJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggal_sampai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTampilkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPendapatan)
                    .addComponent(jButton1))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        tampilkanLaporan();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void comboJenisLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisLaporanActionPerformed
        // TODO add your handling code here:
    // OPSI 1: Kosongkan Tabel segera setelah pilihan diubah
    // Ini memberikan indikasi bahwa user harus menekan tombol "Tampilkan"
    
    // Tentukan header kolom kosong (atau kosongkan model)
    String jenis = (String) comboJenisLaporan.getSelectedItem();
    DefaultTableModel modelKosong = new DefaultTableModel();
    
    // Atur header agar pengguna tahu data apa yang diharapkan
    if (jenis.equals("Laporan Pendapatan")) {
        modelKosong.setColumnIdentifiers(new Object[]{"ID Transaksi", "Tanggal Bayar", "Nama Pasien", "Total Biaya (Rp)"});
    } // ... tambahkan untuk jenis laporan lain
    
    tblLaporan.setModel(modelKosong);
    lblTotalPendapatan.setText("Total Pendapatan: [Tekan Tampilkan Laporan]");
    }//GEN-LAST:event_comboJenisLaporanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JComboBox<String> comboJenisLaporan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalPendapatan;
    private javax.swing.JLabel lbl_PilihLaporan;
    private javax.swing.JLabel lbl_dariTanggal;
    private com.toedter.calendar.JDateChooser taggal_dari;
    private com.toedter.calendar.JDateChooser tanggal_sampai;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables

    private void initTampilanAwal() {
        // 1. Atur model tabel menjadi kosong atau dengan header generik
        DefaultTableModel modelAwal = new DefaultTableModel(new Object[]{"ID Transaksi", "Tanggal Bayar", "Nama Pasien", "Total Biaya (Rp)"}, 0);
        tblLaporan.setModel(modelAwal);
    
        // 2. Set Label Ringkasan
        lblTotalPendapatan.setText("Total Pendapatan: -");
    
        // 3. Pilih item pertama di JComboBox (Opsional: agar trigger action)
        comboJenisLaporan.setSelectedIndex(0); 
    
        // Jika Anda ingin JDateChooser kosong, gunakan:
        // dateChooserDari.setDate(null);
        // dateChooserSampai.setDate(null);
    }

private void tampilkanLaporan() {
    String jenisLaporan = (String) comboJenisLaporan.getSelectedItem();
    
    // Buat model baru
    DefaultTableModel model = new DefaultTableModel(); 
    
    // Logika Pengaturan Kolom dan Data Dummy
    switch (jenisLaporan) {
        case "Laporan Pendapatan" -> {
            model.setColumnIdentifiers(new Object[]{"ID Transaksi", "Tanggal Bayar", "Nama Pasien", "Total Biaya (Rp)"});
            // Data dummy
            model.addRow(new Object[]{"P001", "2025-10-25", "Budi Santoso", 150000.00});
            lblTotalPendapatan.setText("Total Pendapatan: Rp. 400.000,00 (Dummy)");
            }
            
        case "Laporan Kunjungan Pasien" -> {
            model.setColumnIdentifiers(new Object[]{"Tanggal Kunjungan", "Nama Dokter", "Nama Pasien", "Status"});
            // Data dummy
            model.addRow(new Object[]{"2025-10-27", "Dr. Aulia", "Budi Santoso", "Selesai"});
            lblTotalPendapatan.setText("Total Pendapatan: N/A");
            }
            
        case "Laporan Penggunaan Obat" -> {
            model.setColumnIdentifiers(new Object[]{"Nama Obat", "Total Terjual", "Satuan"});
            // Data dummy
            model.addRow(new Object[]{"Paracetamol 500mg", 50, "Tablet"});
            lblTotalPendapatan.setText("Total Pendapatan: N/A");
            }
            
        default -> {
            return;
            }
    }
    
    // Set Model ke JTable
    tblLaporan.setModel(model);
    tblLaporan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
}



}

