/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manajemen;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kusuma
 */
public class JPanel_Manajemen_User extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Manajemen_User
     */
    public JPanel_Manajemen_User() {
        initComponents();
        loadUserData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cariUser = new javax.swing.JLabel();
        txtCariUser = new javax.swing.JTextField();
        btnCariUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnTambahUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnHapusUser = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_cariUser.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_cariUser.setForeground(new java.awt.Color(0, 0, 0));
        btn_cariUser.setText("Cari User");

        txtCariUser.setBackground(new java.awt.Color(255, 255, 255));
        txtCariUser.setForeground(new java.awt.Color(0, 0, 0));

        btnCariUser.setBackground(new java.awt.Color(51, 51, 255));
        btnCariUser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCariUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCariUser.setText("Cari");

        tblUser.setBackground(new java.awt.Color(255, 255, 255));
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Id", "Username", "Nama Lengkap", "Role"
            }
        ));
        tblUser.setGridColor(new java.awt.Color(204, 204, 204));
        tblUser.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tblUser.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblUser);

        btnTambahUser.setBackground(new java.awt.Color(51, 153, 255));
        btnTambahUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnTambahUser.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahUser.setText("Tambah User");
        btnTambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahUserActionPerformed(evt);
            }
        });

        btnEditUser.setBackground(new java.awt.Color(255, 153, 51));
        btnEditUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnEditUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEditUser.setText("Edit User");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnHapusUser.setBackground(new java.awt.Color(255, 51, 51));
        btnHapusUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnHapusUser.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusUser.setText("Hapus User");
        btnHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusUserActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 51, 255));
        btnRefresh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cariUser)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 134, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cariUser)
                    .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariUser)
                    .addComponent(btnRefresh))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnTambahUser)
                .addGap(18, 18, 18)
                .addComponent(btnEditUser)
                .addGap(18, 18, 18)
                .addComponent(btnHapusUser)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahUserActionPerformed
        // TODO add your handling code here:
        // Membuat instance JDialog_Form_User
    // Asumsi: JDialog_Form_User memiliki constructor (Frame parent, boolean modal)
    
    // Pastikan Anda mengubah 'parentFrame' dengan instance JFrame utama Anda jika diperlukan
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this); 
    
    JDialog_Form_User form = new JDialog_Form_User(parentFrame, true);
    form.setTitle("Tambah User Baru");
    form.setVisible(true);
    
    // Setelah dialog ditutup, muat ulang data (simulasi)
    loadUserData();
    }//GEN-LAST:event_btnTambahUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUser.getSelectedRow();
    
    // 1. Cek apakah ada baris yang dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Mohon pilih baris data user yang ingin diubah.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Ambil Data dari Baris Terpilih (Simulasi Pengambilan Data)
    // Asumsi: Kolom di tblUser sesuai urutan: ID, Username, Nama Lengkap, Role
    DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
    
    String userId = model.getValueAt(selectedRow, 0).toString();
    String username = model.getValueAt(selectedRow, 1).toString();
    String namaLengkap = model.getValueAt(selectedRow, 2).toString();
    String role = model.getValueAt(selectedRow, 3).toString();

    // 3. Tampilkan JDialog_Form_User dengan data yang telah diisi
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this); 
    
    // Asumsi JDialog_Form_User memiliki constructor khusus untuk Edit
    // KARENA kita tidak tahu constructor Anda, kita gunakan constructor default dan setter
    JDialog_Form_User form = new JDialog_Form_User(parentFrame, true);
    form.setTitle("Edit User: " + username);
    
    // PENTING: Anda harus menambahkan metode 'setter' di JDialog_Form_User
    // untuk mengisi data ke txt_user_id, txt_username, dll.
    form.setUserDataForEdit(userId, username, namaLengkap, role); // <-- Asumsi metode ini ada
    
    form.setVisible(true);

    // 4. Setelah dialog ditutup, muat ulang data (simulasi)
    loadUserData();
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusUserActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUser.getSelectedRow();

    // 1. Cek apakah ada baris yang dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Mohon pilih baris data user yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Ambil data kunci
    DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
    String userId = model.getValueAt(selectedRow, 0).toString();
    String username = model.getValueAt(selectedRow, 1).toString();

    // 3. Konfirmasi Hapus
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus User ID " + userId + " (" + username + ")?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // 4. Simulasi Hapus Data (Langsung Hapus dari Model Tabel)
        
        model.removeRow(selectedRow); // Menghapus baris dari tampilan tabel
        
        JOptionPane.showMessageDialog(this, 
                "User " + username + " berhasil dihapus. (SIMULASI)", 
                "Hapus Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
        
        // 5. Muat ulang data jika perlu (saat ini tidak perlu karena sudah dihapus dari model)
        // loadUserData(); 
    }
    }//GEN-LAST:event_btnHapusUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambahUser;
    private javax.swing.JLabel btn_cariUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtCariUser;
    // End of variables declaration//GEN-END:variables

private void loadUserData() {
    DefaultTableModel model = new DefaultTableModel();
    
    // 1. Atur Header Kolom
    model.setColumnIdentifiers(new Object[]{"User ID", "Username", "Nama Lengkap", "Role"});
    
    // 2. Tambahkan Data Dummy
    model.addRow(new Object[]{"U001", "superadmin", "Manajemen Klinik", "Manajemen"});
    model.addRow(new Object[]{"U002", "dr.agus", "Agus Santoso, Sp.A", "Dokter"});
    model.addRow(new Object[]{"U003", "kasir01", "Rina Amelia", "Kasir"});
    model.addRow(new Object[]{"U004", "apoteker01", "Fahmi Nur", "Apoteker"});
    
    // 3. Set Model ke JTable
    tblUser.setModel(model);
    tblUser.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
}

}
