/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manajemen;
import Database.KoneksiDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public final class JPanel_Manajemen_Dokter extends javax.swing.JPanel {
    
    private final ImageIcon searchIcon = new ImageIcon(getClass().getResource("/search.png"));

    /**
     * Creates new form JPanel_Manajemen_Dokter
     */
    public JPanel_Manajemen_Dokter() {
        initComponents();
        
        // Menjadwalkan update gambar setelah ukuran tombol tersedia
        SwingUtilities.invokeLater(() -> {
            // Sesuaikan ukuran gambar
            btnCari.setIcon(new ImageIcon(searchIcon.getImage().getScaledInstance(btnCari.getWidth(), btnCari.getHeight(), Image.SCALE_SMOOTH)));
        });
        
        tblDokter.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblDokter.getTableHeader().setOpaque(false);
        tblDokter.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblDokter.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih

//        loadDataToTable(null);
    }
    public void loadDataDokter() {
        
    }
    public void loadDataDokter(String searchTerm) {
//        // 1. Dapatkan model tabel
//        DefaultTableModel model = (DefaultTableModel) tblDokter.getModel();
//
//        // 2. Kosongkan tabel (hapus baris lama)
//        model.setRowCount(0);
//
//        // 3. Buat query SQL dasar
//        String sql = "SELECT id_dokter, nama_dokter, spesialisasi, no_telepon FROM dokter";
//
//        // 4. Tambahkan kondisi WHERE jika ada searchTerm
//        if (searchTerm != null && !searchTerm.trim().isEmpty()) {
//            sql += " WHERE nama_dokter LIKE ? OR dokter_id LIKE ?";
//        }
//
//        // 5. Gunakan try-with-resources untuk koneksi
//        try (Connection conn = Koneksi.getConnection(); // Asumsi Anda punya kelas Koneksi
//             PreparedStatement pstmt = conn.prepareStatement(sql)) {
//
//            // 6. Set parameter pencarian jika ada
//            if (searchTerm != null && !searchTerm.trim().isEmpty()) {
//                String likeTerm = "%" + searchTerm + "%";
//                pstmt.setString(1, likeTerm);
//                pstmt.setString(2, likeTerm);
//            }
//
//            // 7. Eksekusi query
//            try (ResultSet rs = pstmt.executeQuery()) {
//                // 8. Looping hasil dan tambahkan ke model tabel
//                while (rs.next()) {
//                        model.addRow(new Object[]{
//                            rs.getString("id_dokter"),
//                            rs.getString("nama_dokter"),
//                            rs.getString("spesialisasi"),
//                            rs.getString("no_telepon")
//                        });
//                    }
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, 
//                    "Gagal memuat data dokter: " + e.getMessage(), 
//                    "Error Database", 
//                    JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace(); // Tampilkan error di console untuk debug
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKontrol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Manajemen Data Dokter");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelKontrol.setBackground(new java.awt.Color(255, 255, 255));

        btnTambah.setBackground(new java.awt.Color(50, 120, 220));
        btnTambah.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah Dokter");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 130, 0));
        btnEdit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Dokter");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(220, 53, 69));
        btnHapus.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Dokter");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(75, 167, 87));
        btnCari.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblDokter.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"D001", "dr. ABCD", "THT", "Laki-laki"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama Lengkap", "Spesialisasi", "No. Telepon"
            }
        ));
        tblDokter.setGridColor(new java.awt.Color(224, 224, 224));
        tblDokter.setRowHeight(30);
        tblDokter.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblDokter.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblDokter.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblDokter);

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblJudul)
                        .addGap(0, 569, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        // 1. Ambil kata kunci dari JTextField
        String searchTerm = txtCari.getText();

        // 2. Panggil method loadDataToTable dengan kata kunci tersebut
        loadDataDokter(searchTerm);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        JDialog_Form_Dokter formDokter = new JDialog_Form_Dokter(null, true, this); // 'this' adalah referensi ke panel ini
        formDokter.setVisible(true);

        loadDataDokter(); // Panggil method yang sudah di-rename
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblDokter.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih data dokter yang ingin Anda edit terlebih dahulu.",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            //            return; // Hentikan eksekusi
        }

        // 3. Ambil ID Pasien dari kolom pertama (index 0)
        String idDokter = tblDokter.getValueAt(selectedRow, 0).toString();

        // 4. Dapatkan frame induk (cara paling aman)
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);

        // 5. Buat dan tampilkan JDialog_Form_Pasien dalam mode EDIT
        //    (Asumsi Anda punya constructor ini)
        JDialog_Form_Dokter formDokter = new JDialog_Form_Dokter(null, true, this, idDokter);
        formDokter.setVisible(true);

        // 6. Setelah form ditutup, muat ulang data di tabel
        //    Kita kirim txtCari.getText() agar pencarian tetap aktif jika ada
        loadDataDokter(txtCari.getText());
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih
        int selectedRow = tblDokter.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih data dokter yang ingin Anda hapus.",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil ID dan Nama untuk konfirmasi
        String idDokter = tblDokter.getValueAt(selectedRow, 0).toString();
        String namaDokter = tblDokter.getValueAt(selectedRow, 1).toString();

        // 4. Tampilkan dialog konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus data dokter:\n" + namaDokter + " (ID: " + idDokter + ")?",
            "Konfirmasi Hapus Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        // 5. Cek jika pengguna menekan "Ya"
        if (pilihan == JOptionPane.YES_OPTION) {
            // 6. Lakukan operasi database
            String sql = "DELETE FROM dokter WHERE dokter_id = ?";

//            try (Connection conn = KoneksiDatabase.connect();
//                PreparedStatement pstmt = conn.prepareStatement(sql)) {
//
//                pstmt.setString(1, idDokter);
//
//                // 7. Eksekusi delete
//                int rowsAffected = pstmt.executeUpdate();
//
//                if (rowsAffected > 0) {
//                    JOptionPane.showMessageDialog(this,
//                        "Data dokter berhasil dihapus.",
//                        "Sukses",
//                        JOptionPane.INFORMATION_MESSAGE);
//
//                    // 8. Muat ulang data (dan bersihkan pencarian)
//                    txtCari.setText(""); // Bersihkan field pencarian
//                    //                    loadDataToTable(null); // Muat ulang semua data
//                } else {
//                    JOptionPane.showMessageDialog(this,
//                        "Data dokter tidak ditemukan (mungkin sudah dihapus).",
//                        "Info",
//                        JOptionPane.INFORMATION_MESSAGE);
//                }
//                loadDataDokter();
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this,
//                    "Gagal menghapus data: " + e.getMessage(),
//                    "Error Database",
//                    JOptionPane.ERROR_MESSAGE);
//                //                e.printStackTrace();
//            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
