/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manajemen;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class JPanel_Dashboard_Manajemen extends javax.swing.JPanel {
    
    private final ImageIcon kunjunganIcon = new ImageIcon(getClass().getResource("/Kunjungan.png"));
    private final ImageIcon pendapatanIcon = new ImageIcon(getClass().getResource("/pendapatan.png"));
    private final ImageIcon patientIcon = new ImageIcon(getClass().getResource("/patient.png"));
    
    
    /**
     * Creates new form JPanel_Dashboard_Admin
     */
    public JPanel_Dashboard_Manajemen() {
        initComponents();
        
        // Menjadwalkan update gambar setelah ukuran tombol tersedia
        SwingUtilities.invokeLater(() -> {
            // Sesuaikan ukuran gambar
            lblIconKunjungan.setIcon(new ImageIcon(kunjunganIcon.getImage().getScaledInstance(lblIconKunjungan.getWidth(), lblIconKunjungan.getHeight(), Image.SCALE_SMOOTH)));
            lblIconPendapatan.setIcon(new ImageIcon(pendapatanIcon.getImage().getScaledInstance(lblIconPendapatan.getWidth(), lblIconPendapatan.getHeight(), Image.SCALE_SMOOTH)));
            lblIconPasien.setIcon(new ImageIcon(patientIcon.getImage().getScaledInstance(lblIconPasien.getWidth(), lblIconPasien.getHeight(), Image.SCALE_SMOOTH)));
        });
        
        loadDashboardData();
    }
    
    public void loadDashboardData() {
        // Contoh (angka_dari_db harus berupa String)
//        lblJumlahPasien.setText(angka_dari_db_pasien);
//        lblJumlahDokter.setText(angka_dari_db_dokter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardTotalKunjungan = new javax.swing.JPanel();
        lblIconKunjungan = new javax.swing.JLabel();
        lblJumlahPasien = new javax.swing.JLabel();
        lblTitlePasien = new javax.swing.JLabel();
        cardTotalPendapatan = new javax.swing.JPanel();
        lblIconPendapatan = new javax.swing.JLabel();
        lblJumlahDokter = new javax.swing.JLabel();
        lblTitleDokter = new javax.swing.JLabel();
        cardPasien = new javax.swing.JPanel();
        lblIconPasien = new javax.swing.JLabel();
        lblJumlahKunjungan = new javax.swing.JLabel();
        lblTitleKunjungan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAksesTambahPasien = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Dashboard");

        lblWelcome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 153, 153));
        lblWelcome.setText("Selamat datang kembali, [Nama Pemilik Klinik]! Ini adalah ringkasan klinik Anda hari ini.");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        cardTotalKunjungan.setBackground(new java.awt.Color(255, 255, 255));
        cardTotalKunjungan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(50, 120, 220)));
        cardTotalKunjungan.setPreferredSize(new java.awt.Dimension(250, 120));

        lblIconKunjungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kunjungan.png"))); // NOI18N

        lblJumlahPasien.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblJumlahPasien.setText("1.420");

        lblTitlePasien.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTitlePasien.setForeground(new java.awt.Color(102, 102, 102));
        lblTitlePasien.setText("Total Kunjungan");

        javax.swing.GroupLayout cardTotalKunjunganLayout = new javax.swing.GroupLayout(cardTotalKunjungan);
        cardTotalKunjungan.setLayout(cardTotalKunjunganLayout);
        cardTotalKunjunganLayout.setHorizontalGroup(
            cardTotalKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardTotalKunjunganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardTotalKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahPasien)
                    .addComponent(lblTitlePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cardTotalKunjunganLayout.setVerticalGroup(
            cardTotalKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardTotalKunjunganLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(cardTotalKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardTotalKunjunganLayout.createSequentialGroup()
                        .addComponent(lblJumlahPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitlePasien)))
                .addGap(23, 23, 23))
        );

        cardTotalPendapatan.setBackground(new java.awt.Color(255, 255, 255));
        cardTotalPendapatan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(25, 135, 84)));
        cardTotalPendapatan.setPreferredSize(new java.awt.Dimension(250, 120));

        lblIconPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendapatan.png"))); // NOI18N

        lblJumlahDokter.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
        lblJumlahDokter.setText("Rp. 150.000.000");

        lblTitleDokter.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTitleDokter.setForeground(new java.awt.Color(102, 102, 102));
        lblTitleDokter.setText("Total Pendapatan");

        javax.swing.GroupLayout cardTotalPendapatanLayout = new javax.swing.GroupLayout(cardTotalPendapatan);
        cardTotalPendapatan.setLayout(cardTotalPendapatanLayout);
        cardTotalPendapatanLayout.setHorizontalGroup(
            cardTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTotalPendapatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahDokter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardTotalPendapatanLayout.setVerticalGroup(
            cardTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardTotalPendapatanLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(cardTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardTotalPendapatanLayout.createSequentialGroup()
                        .addComponent(lblJumlahDokter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleDokter)))
                .addGap(23, 23, 23))
        );

        cardPasien.setBackground(new java.awt.Color(255, 255, 255));
        cardPasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(255, 193, 7)));
        cardPasien.setPreferredSize(new java.awt.Dimension(250, 120));

        lblIconPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patient.png"))); // NOI18N

        lblJumlahKunjungan.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblJumlahKunjungan.setText("125");

        lblTitleKunjungan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTitleKunjungan.setForeground(new java.awt.Color(102, 102, 102));
        lblTitleKunjungan.setText("Pasien Baru");

        javax.swing.GroupLayout cardPasienLayout = new javax.swing.GroupLayout(cardPasien);
        cardPasien.setLayout(cardPasienLayout);
        cardPasienLayout.setHorizontalGroup(
            cardPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahKunjungan)
                    .addComponent(lblTitleKunjungan))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        cardPasienLayout.setVerticalGroup(
            cardPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPasienLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cardPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardPasienLayout.createSequentialGroup()
                        .addComponent(lblJumlahKunjungan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleKunjungan)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Akses Cepat");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnAksesTambahPasien.setBackground(new java.awt.Color(50, 120, 220));
        btnAksesTambahPasien.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAksesTambahPasien.setForeground(new java.awt.Color(255, 255, 255));
        btnAksesTambahPasien.setText("Lihat Semua Laporan");
        btnAksesTambahPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAksesTambahPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksesTambahPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcome)
                            .addComponent(lblJudul)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnAksesTambahPasien)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cardTotalKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cardTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cardPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJudul)
                .addGap(12, 12, 12)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardTotalKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAksesTambahPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAksesTambahPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksesTambahPasienActionPerformed
        // TODO add your handling code here:
        Container parent = this.getParent();

        // 2. Dapatkan CardLayout dari panelContent
        CardLayout cl = (CardLayout) parent.getLayout();

        // 3. Panggil kartu "cardPasien"
        cl.show(parent, "cardLaporan");
    }//GEN-LAST:event_btnAksesTambahPasienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksesTambahPasien;
    private javax.swing.JPanel cardPasien;
    private javax.swing.JPanel cardTotalKunjungan;
    private javax.swing.JPanel cardTotalPendapatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIconKunjungan;
    private javax.swing.JLabel lblIconPasien;
    private javax.swing.JLabel lblIconPendapatan;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlahDokter;
    private javax.swing.JLabel lblJumlahKunjungan;
    private javax.swing.JLabel lblJumlahPasien;
    private javax.swing.JLabel lblTitleDokter;
    private javax.swing.JLabel lblTitleKunjungan;
    private javax.swing.JLabel lblTitlePasien;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
