/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apoteker;

import java.awt.Color;
import java.awt.FlowLayout;
/**
 *
 * @author Joyrich
 */
public class JDialog_Proses_Resep extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialog_Proses_Resep.class.getName());

    /**
     * Creates new form JDialog_Proses_Resep
     */
    public JDialog_Proses_Resep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanel1 = new javax.swing.JPanel();
        lblInfoPasien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailResep = new javax.swing.JTable();
        // Menggunakan jPanel2 sebagai panel SOUTH (Aksi & Peringatan)
        jPanel2 = new javax.swing.JPanel(); 
        lblPeringatanStok = new javax.swing.JLabel();
        btnSelesaiSerahkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblInfoPasien.setText("Info pasien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lblInfoPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoPasien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblDetailResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Obat", "Jumlah", "Dosis", "Stok Saat Ini"
            }
        ));
        jScrollPane1.setViewportView(tblDetailResep);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        // --- PENGATURAN PANEL SOUTH (jPanel2) ---
        // FlowLayout sudah menjadi default, tetapi kita pastikan
        jPanel2.setLayout(new FlowLayout(FlowLayout.CENTER)); 

        // 1. Pengaturan JLabel Peringatan
        lblPeringatanStok.setForeground(Color.RED); 
        lblPeringatanStok.setText("⚠️ PERINGATAN: Stok obat tidak cukup. Transaksi dibatalkan.");
        // Menyembunyikan komponen secara default
        lblPeringatanStok.setVisible(false); 
        
        jPanel2.add(lblPeringatanStok);

        // 2. Pengaturan JButton
        btnSelesaiSerahkan.setText("Selesai & Serahkan Obat");
        jPanel2.add(btnSelesaiSerahkan);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>    /**
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInfoPasien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailResep = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblPeringatanStok = new javax.swing.JLabel();
        btnSelesaiSerahkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Resep");

        lblInfoPasien.setText("Info pasien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lblInfoPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoPasien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblDetailResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Obat", "Jumlah", "Dosis", "Stok Saat Ini"
            }
        ));
        jScrollPane1.setViewportView(tblDetailResep);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblPeringatanStok.setForeground(new java.awt.Color(255, 0, 0));
        lblPeringatanStok.setText("PERINGATAN: Stok obat tidak cukup. Transaksi dibatalkan");
        jPanel2.add(lblPeringatanStok);

        btnSelesaiSerahkan.setText("Selesai & Serahkan Obat");
        jPanel2.add(btnSelesaiSerahkan);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialog_Proses_Resep dialog = new JDialog_Proses_Resep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelesaiSerahkan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfoPasien;
    private javax.swing.JLabel lblPeringatanStok;
    private javax.swing.JTable tblDetailResep;
    // End of variables declaration//GEN-END:variables
}
