package Apoteker;

import java.awt.CardLayout;
import java.util.logging.Level;
import com.formdev.flatlaf.FlatLightLaf; // Atau FlatDarkLaf, FlatIntelliJLaf, dll.

public class JFrame_Main_Apoteker extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Main_Apoteker.class.getName());

    private JPanel_Antrean_Resep panelAntreanResep;
    private JPanel_Manajemen_Obat panelManajemenObat;
    /**
     * Creates new form JFrame_Main_Apoteker
     */
    
    public JFrame_Main_Apoteker() {
        initComponents();
        setupMainFrame();
    }

    private void setupMainFrame() {
        // Inisialisasi Panel
        panelAntreanResep = new JPanel_Antrean_Resep(this); // Mengirim reference frame
        panelManajemenObat = new JPanel_Manajemen_Obat(this); // Mengirim reference frame
        
        // Dapatkan CardLayout dari panelKonten
        CardLayout cardLayout = (CardLayout) panelKonten.getLayout();
        
        panelKonten.add(panelAntreanResep, "AntreanResep");
        panelKonten.add(panelManajemenObat, "ManajemenObat");
        
        cardLayout.show(panelKonten, "AntreanResep");
        
        btnAntreanResep.addActionListener(e -> cardLayout.show(panelKonten, "AntreanResep"));
        btnManajemenObat.addActionListener(e -> cardLayout.show(panelKonten, "ManajemenObat"));
        
        // Mengubah teks btnAntreanResep agar tidak terpotong
        btnAntreanResep.setText("Antrean Resep");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAntreanResep = new javax.swing.JButton();
        btnManajemenObat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));

        btnAntreanResep.setText("Antrean Resep");

        btnManajemenObat.setText("Manajemen Obat");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Apoteker");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManajemenObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAntreanResep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAntreanResep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenObat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelKonten.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelKonten, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            FlatLightLaf.setup(); 
  
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to initialize FlatLaf", ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Main_Apoteker().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntreanResep;
    private javax.swing.JButton btnManajemenObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelKonten;
    // End of variables declaration//GEN-END:variables
}
