package Apoteker;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLightLaf;
import Main.JFrame_Login;
import javax.swing.JFrame;

public class JFrame_Main_Apoteker extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Main_Apoteker.class.getName());

    private JPanel_Antrean_Resep panelAntreanResep;
    private JPanel_Manajemen_Obat panelManajemenObat;
  
    public JFrame_Main_Apoteker() {
        initComponents();
        setupMainFrame();
        // Memusatkan dan memaksimalkan window
        this.setLocationRelativeTo(null); 
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void setupMainFrame() {
        panelAntreanResep = new JPanel_Antrean_Resep(this);
        panelManajemenObat = new JPanel_Manajemen_Obat(this);
        
        CardLayout cardLayout = (CardLayout) panelKonten.getLayout();
        
        panelKonten.add(panelAntreanResep, "AntreanResep");
        panelKonten.add(panelManajemenObat, "ManajemenObat");
        
        cardLayout.show(panelKonten, "AntreanResep");
        
        btnAntreanResep.addActionListener(e -> cardLayout.show(panelKonten, "AntreanResep"));
        btnManajemenObat.addActionListener(e -> cardLayout.show(panelKonten, "ManajemenObat"));
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAntreanResep = new javax.swing.JButton();
        btnManajemenObat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Apoteker");
        setName("Form"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));
        jPanel1.setName("jPanel1"); // NOI18N

        btnAntreanResep.setText("Antrean Resep");
        btnAntreanResep.setName("btnAntreanResep"); // NOI18N

        btnManajemenObat.setText("Manajemen Obat");
        btnManajemenObat.setName("btnManajemenObat"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Apoteker");
        jLabel1.setName("jLabel1"); // NOI18N

        btn_logout.setBackground(new java.awt.Color(220, 53, 69));
        btn_logout.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("[➜  Logout");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.setName("btn_logout"); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_logout)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManajemenObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAntreanResep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAntreanResep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenObat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelKonten.setName("panelKonten"); // NOI18N
        panelKonten.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelKonten, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        // Tampilkan konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (pilihan == JOptionPane.YES_OPTION) {
            // Buka kembali jendela Login
            new JFrame_Login().setVisible(true);

            // Tutup dashboard ini
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            FlatLightLaf.setup(); 
  
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to initialize FlatLaf", ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Main_Apoteker().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntreanResep;
    private javax.swing.JButton btnManajemenObat;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelKonten;
    // End of variables declaration//GEN-END:variables
}
