/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Apoteker;

import java.awt.Frame;

public class JPanel_Antrean_Resep extends javax.swing.JPanel {
    private final Frame parentFrame; // Menyimpan reference Frame utama
    public JPanel_Antrean_Resep(Frame parent) {
        initComponents();
        this.parentFrame = parent;
        setupListeners();
    }
    
    private void setupListeners() {
        btnProsesResep.addActionListener(e -> {
            // Logika untuk mendapatkan resep terpilih dari tabel
            // ...
            
            // Tampilkan JDialog_Proses_Resep
            JDialog_Proses_Resep dialog = new JDialog_Proses_Resep(parentFrame, true);
            dialog.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAntreanResep = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnProsesResep = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Antrean Resep Belum Diambil");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tblAntreanResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Resep", "Waktu", "Nama Pasien", "Nama Dokter"
            }
        ));
        jScrollPane1.setViewportView(tblAntreanResep);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnProsesResep.setText("Proses Resep Terpilih");
        jPanel1.add(btnProsesResep);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProsesResep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAntreanResep;
    // End of variables declaration//GEN-END:variables
}
