/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dokter;

import Resepsionis.JPanel_Informasi_Dokter;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JDialog_Rekam_Medis extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialog_Rekam_Medis.class.getName());

    /**
     * Creates new form JDialog_Form_Dokter
     */
    private String idDokterToEdit = null;
    // Tambahkan juga referensi ke panel tabel (opsional tapi berguna)
    private JPanel_Informasi_Dokter panelManajemen;
    
    private String idKunjungan;
    private String idPasien;
    private javax.swing.table.DefaultTableModel modelResep;
    
    public JDialog_Rekam_Medis(java.awt.Frame parent, boolean modal, 
                           String idKunjungan, String idPasien, String namaPasien) {
    super(parent, modal);
    initComponents();

    // Simpan data yang dikirim
    this.idKunjungan = idKunjungan;
    this.idPasien = idPasien;

    // Set label info pasien
    lblNamaPasien.setText(namaPasien);
    lblIdPasien.setText(idPasien);
    lblIdKunjungan.setText(idKunjungan);

    // Panggil method inisialisasi kustom
    initCustomComponents();
    loadDataObat();
}
    
    public JDialog_Rekam_Medis(java.awt.Frame parent, boolean modal, JPanel_Informasi_Dokter panelManajemen, String idDokter) {
        

        this.idDokterToEdit = idDokter; // Simpan ID untuk diedit

        

        // Panggil method untuk memuat data lama
        loadDataForEdit();
    }
    
    class ObatItem {
        public String id;
        public String nama;

        public ObatItem(String id, String nama) {
            this.id = id;
            this.nama = nama;
        }

        @Override
        public String toString() {
            return nama; // Tampilkan nama di combo box
        }
    }
    
    private void initCustomComponents() {
        setLocationRelativeTo(null);

        // Siapkan JSpinner (angka 1-100)
        spinnerJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        // Siapkan Model Tabel Resep
//        modelResep = (DefaultTableModel) tblResep.getModel();

        // Sembunyikan kolom ID Obat (kolom 0)
        tblResep.getColumnModel().getColumn(0).setMinWidth(0);
        tblResep.getColumnModel().getColumn(0).setMaxWidth(0);

        // Style header (opsional tapi bagus)
        tblResep.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        // Placeholder
        txtDosis.putClientProperty("JTextField.placeholderText", "Contoh: 3 x 1 hari sesudah makan");
    }

    private void loadDataObat() {
        // Mengisi JComboBox 'comboObat' dari database
        try {
            // SQL: "SELECT id_obat, nama_obat FROM obat WHERE stok > 0 ORDER BY nama_obat"
            // ... (Eksekusi query) ...

            // while (rs.next()) {
            //    comboObat.addItem(new ObatItem(rs.getString("id_obat"), rs.getString("nama_obat")));
            // }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data obat: " + e.getMessage());
        }
    }

    private String generateNewDokterID() {
        // Buat logika Anda di sini, misal query ke DB untuk ID terakhir + 1
        // atau format P-TahunBulan-001
        return "D202510-001"; // Contoh
    }

    private void loadDataForEdit() {
        // 1. Buat koneksi ke database
        // 2. Jalankan SQL: SELECT * FROM dokter WHERE id_dokter = ? (gunakan idDokterToEdit)
        // 3. Ambil hasilnya (ResultSet)
        // 4. Set setiap komponen:
        //    txtNamaPasien.setText(rs.getString("nama_dokter"));
        //    dcTanggalLahir.setDate(rs.getDate("tanggal_lahir"));
        //    txtAlamat.setText(rs.getString("alamat"));
        //    if (rs.getString("jenis_kelamin").equals("Laki-laki")) {
        //        rbLakiLaki.setSelected(true);
        //    } else {
        //        rbPerempuan.setSelected(true);
        //    }
        //    ... dan seterusnya
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scrollDialog = new javax.swing.JScrollPane();
        panelForm = new javax.swing.JPanel();
        panelInfoPasien = new javax.swing.JPanel();
        lblNamaPasien = new javax.swing.JLabel();
        lblIdPasien = new javax.swing.JLabel();
        lblIdKunjungan = new javax.swing.JLabel();
        lblIdKunjungan1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnamnesa = new javax.swing.JTextArea();
        lblIdKunjungan2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiagnosa = new javax.swing.JTextArea();
        panelResep = new javax.swing.JPanel();
        lblNamaPasien1 = new javax.swing.JLabel();
        comboObat = new javax.swing.JComboBox<>();
        lblNamaPasien2 = new javax.swing.JLabel();
        spinnerJumlah = new javax.swing.JSpinner();
        lblNamaPasien3 = new javax.swing.JLabel();
        txtDosis = new javax.swing.JTextField();
        btnTambahObat = new javax.swing.JButton();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblResep = new javax.swing.JTable();
        btnHapusObat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSimpanRekamMedis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Pemeriksaan Rekam Medis");
        setModal(true);

        panelForm.setBackground(new java.awt.Color(255, 255, 255));
        panelForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));

        panelInfoPasien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N

        lblNamaPasien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNamaPasien.setText("Nama Pasien");

        lblIdPasien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblIdPasien.setText("ID Pasien");

        lblIdKunjungan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblIdKunjungan.setText("ID Kunjungan");

        javax.swing.GroupLayout panelInfoPasienLayout = new javax.swing.GroupLayout(panelInfoPasien);
        panelInfoPasien.setLayout(panelInfoPasienLayout);
        panelInfoPasienLayout.setHorizontalGroup(
            panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaPasien)
                    .addComponent(lblIdPasien)
                    .addComponent(lblIdKunjungan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoPasienLayout.setVerticalGroup(
            panelInfoPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPasienLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdKunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIdKunjungan1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblIdKunjungan1.setForeground(java.awt.Color.black);
        lblIdKunjungan1.setText("Anamnesa / Keluhan Pasien");

        txtAnamnesa.setColumns(20);
        txtAnamnesa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAnamnesa.setLineWrap(true);
        txtAnamnesa.setRows(5);
        txtAnamnesa.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAnamnesa);

        lblIdKunjungan2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblIdKunjungan2.setForeground(java.awt.Color.black);
        lblIdKunjungan2.setText("Diagnosa / Pemeriksaan Fisik");

        txtDiagnosa.setColumns(20);
        txtDiagnosa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDiagnosa.setLineWrap(true);
        txtDiagnosa.setRows(5);
        txtDiagnosa.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDiagnosa);

        panelResep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resep Obat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N

        lblNamaPasien1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNamaPasien1.setText("Obat");

        comboObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paracetamol", "Ibuprofen", "Amoxicillin" }));

        lblNamaPasien2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNamaPasien2.setText("Jumlah");

        lblNamaPasien3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNamaPasien3.setText("Dosis");

        txtDosis.setText("3 x 1 hari");

        btnTambahObat.setBackground(new java.awt.Color(50, 120, 220));
        btnTambahObat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnTambahObat.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahObat.setText("➕  Tambah ke Resep");
        btnTambahObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahObatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResepLayout = new javax.swing.GroupLayout(panelResep);
        panelResep.setLayout(panelResepLayout);
        panelResepLayout.setHorizontalGroup(
            panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelResepLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTambahObat))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResepLayout.createSequentialGroup()
                        .addComponent(lblNamaPasien1)
                        .addGap(33, 33, 33)
                        .addComponent(comboObat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResepLayout.createSequentialGroup()
                        .addGroup(panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaPasien2)
                            .addComponent(lblNamaPasien3))
                        .addGap(18, 18, 18)
                        .addGroup(panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerJumlah)
                            .addComponent(txtDosis))))
                .addGap(33, 33, 33))
        );
        panelResepLayout.setVerticalGroup(
            panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResepLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboObat, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPasien2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPasien3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTambahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tblResep.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"D001", "Paracetamol", "3", "3 x 1 hari"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Obat", "Nama Obat", "Jumlah", "Dosis"
            }
        ));
        tblResep.setGridColor(new java.awt.Color(224, 224, 224));
        tblResep.setRowHeight(30);
        tblResep.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblResep.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblResep.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblResep);

        btnHapusObat.setBackground(new java.awt.Color(220, 53, 69));
        btnHapusObat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHapusObat.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusObat.setText("❌  Hapus dari Resep");
        btnHapusObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusObatActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnSimpanRekamMedis.setBackground(new java.awt.Color(50, 120, 220));
        btnSimpanRekamMedis.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSimpanRekamMedis.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanRekamMedis.setText("Simpan Rekam Medis & Selesaikan Kunjungan");
        btnSimpanRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanRekamMedisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                    .addComponent(panelResep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(lblIdKunjungan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(lblIdKunjungan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpanRekamMedis))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(btnHapusObat)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInfoPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdKunjungan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdKunjungan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnHapusObat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpanRekamMedis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        scrollDialog.setViewportView(panelForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusObatActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblResep.getSelectedRow();
        if (selectedRow != -1) {
            modelResep.removeRow(selectedRow); // Hapus baris dari model
        } else {
            JOptionPane.showMessageDialog(this, "Pilih obat di tabel resep yang ingin dihapus.");
        }
    }//GEN-LAST:event_btnHapusObatActionPerformed

    private void btnSimpanRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanRekamMedisActionPerformed
        // TODO add your handling code here:
        String anamnesa = txtAnamnesa.getText();
        String diagnosa = txtDiagnosa.getText();

        if (anamnesa.trim().isEmpty() || diagnosa.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Anamnesa dan Diagnosa wajib diisi!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Dapatkan koneksi database
        // Connection conn = ... (misal: Koneksi.getConnection());

        try {
            // --- MULAI TRANSAKSI ---
            // conn.setAutoCommit(false);

            // 1. INSERT ke tabel 'rekam_medis'
            //    SQL: "INSERT INTO rekam_medis (id_kunjungan, anamnesa, diagnosa) VALUES (?, ?, ?)"
            //    (Gunakan PreparedStatement, set idKunjungan, anamnesa, diagnosa)
            //    ... (execute INSERT rekam_medis) ...

            //    Ambil ID rekam medis yang baru saja dibuat
            //    ResultSet generatedKeys = pstmt.getGeneratedKeys();
            //    String idRekamMedisBaru = "";
            //    if (generatedKeys.next()) {
            //        idRekamMedisBaru = generatedKeys.getString(1);
            //    } else {
            //        throw new SQLException("Gagal mendapatkan ID rekam medis.");
            //    }

            // 2. Cek apakah ada resep di tabel
            if (modelResep.getRowCount() > 0) {
                // 3. Jika ada, INSERT ke tabel 'resep'
                //    SQL: "INSERT INTO resep (rekam_medis_id, tanggal_resep) VALUES (?, NOW())"
                //    (set idRekamMedisBaru)
                //    ... (execute INSERT resep) ...

                //    Ambil ID resep yang baru saja dibuat
                //    (Gunakan getGeneratedKeys() lagi)
                //    String idResepBaru = ...

                // 4. Looping JTable dan INSERT ke 'detail_resep'
                //    String sqlDetail = "INSERT INTO detail_resep (resep_id, obat_id, jumlah, dosis) VALUES (?, ?, ?, ?)";
                //    PreparedStatement pstmtDetail = conn.prepareStatement(sqlDetail);

                //    for (int i = 0; i < modelResep.getRowCount(); i++) {
                //        String idObat = modelResep.getValueAt(i, 0).toString();
                //        int jumlah = (Integer) modelResep.getValueAt(i, 2);
                //        String dosis = modelResep.getValueAt(i, 3).toString();
                //
                //        pstmtDetail.setString(1, idResepBaru);
                //        pstmtDetail.setString(2, idObat);
                //        pstmtDetail.setInt(3, jumlah);
                //        pstmtDetail.setString(4, dosis);
                //        pstmtDetail.addBatch(); // Tambah ke batch
                //    }
                //    pstmtDetail.executeBatch(); // Eksekusi semua INSERT detail resep
            }

            // 5. UPDATE status kunjungan
            //    SQL: "UPDATE kunjungan SET status_kunjungan = 'Selesai' WHERE id_kunjungan = ?"
            //    (set idKunjungan)
            //    ... (execute UPDATE kunjungan) ...

            // --- SELESAI TRANSAKSI ---
            // conn.commit();

            JOptionPane.showMessageDialog(this, "Rekam medis berhasil disimpan!");
            this.dispose(); // Tutup form

        } catch (Exception e) {
            // Jika terjadi error, batalkan semua
            // try { conn.rollback(); } catch (SQLException ex) { ... }
            JOptionPane.showMessageDialog(this, "GAGAL MENYIMPAN DATA: " + e.getMessage(), "Error Transaksi", JOptionPane.ERROR_MESSAGE);
        } finally {
            // try { conn.setAutoCommit(true); } catch (SQLException ex) { ... }
        }
    }//GEN-LAST:event_btnSimpanRekamMedisActionPerformed

    private void btnTambahObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahObatActionPerformed
        // TODO add your handling code here:
        ObatItem item = (ObatItem) comboObat.getSelectedItem();
        int jumlah = (Integer) spinnerJumlah.getValue();
        String dosis = txtDosis.getText();

        if (dosis.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dosis tidak boleh kosong!");
            return;
        }

        // Tambahkan ke JTable
        modelResep.addRow(new Object[]{
            item.id,
            item.nama,
            jumlah,
            dosis
        });

        // Reset input
        txtDosis.setText("");
        spinnerJumlah.setValue(1);
    }//GEN-LAST:event_btnTambahObatActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusObat;
    private javax.swing.JButton btnSimpanRekamMedis;
    private javax.swing.JButton btnTambahObat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboObat;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdKunjungan;
    private javax.swing.JLabel lblIdKunjungan1;
    private javax.swing.JLabel lblIdKunjungan2;
    private javax.swing.JLabel lblIdPasien;
    private javax.swing.JLabel lblNamaPasien;
    private javax.swing.JLabel lblNamaPasien1;
    private javax.swing.JLabel lblNamaPasien2;
    private javax.swing.JLabel lblNamaPasien3;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelInfoPasien;
    private javax.swing.JPanel panelResep;
    private javax.swing.JScrollPane scrollDialog;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JSpinner spinnerJumlah;
    private javax.swing.JTable tblResep;
    private javax.swing.JTextArea txtAnamnesa;
    private javax.swing.JTextArea txtDiagnosa;
    private javax.swing.JTextField txtDosis;
    // End of variables declaration//GEN-END:variables
}
