/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dokter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import Database.KoneksiDatabase;
import Dokter.SessionDokter;

import Main.JFrame_Login;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JFrame_Main_Dokter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Main_Dokter.class.getName());
    private String loggedInDoctorId;

    private String loadDataDokterAndGetId() {
    String dokterId = null;
    try {
        System.out.println("LOGIN USER ID = " + SessionDokter.userId);
        Connection conn = KoneksiDatabase.getConnection();
        String sql = """
            SELECT u.nama_lengkap, d.spesialisasi, d.dokter_id
            FROM dokter d
            JOIN user u ON d.user_id = u.user_id
            WHERE d.user_id = ?
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, SessionDokter.userId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            lblNamaDokter.setText("dr. " + rs.getString("nama_lengkap"));
            lblSpesialisasi.setText(rs.getString("spesialisasi"));
            dokterId = rs.getString("dokter_id");
            System.out.println("Found dokter_id: " + dokterId);
        } else {
            lblNamaDokter.setText("Dokter tidak ditemukan");
            System.err.println("ERROR: User ID " + SessionDokter.userId + " not linked to any dokter!");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
    return dokterId;
}


    /**
     * Creates new form JFrame_Main_Admin
     */
    public JFrame_Main_Dokter() {
    initComponents();
    
    this.setLocationRelativeTo(null);
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    // === DAPATKAN DOKTER_ID DAN DATA DOKTER ===
    String dokterId = loadDataDokterAndGetId();
    
    if (dokterId == null) {
        JOptionPane.showMessageDialog(this,
            "Akun tidak terhubung dengan data dokter. Hubungi admin.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return; // Atau redirect ke login
    }
    
    // === CARD LAYOUT ===
    JPanel_Antrean_Pasien panelAntrean = new JPanel_Antrean_Pasien(dokterId);

    JPanel_Riwayat_Rekam_Medis panelRiwayat = new JPanel_Riwayat_Rekam_Medis();

    panelContent.add(panelAntrean, "cardAntrean");
    panelContent.add(panelRiwayat, "cardRiwayat");

    CardLayout cl = (CardLayout) panelContent.getLayout();
    cl.show(panelContent, "cardAntrean");
}
    
    // --- BUAT CONSTRUCTOR BARU INI ---
    public JFrame_Main_Dokter(String idDokter, String namaDokter, String spesialisasi) {
        this(); // Memanggil constructor default di atas untuk menjalankan initComponents()

        // Set label di sidebar dengan data yang dikirim
        lblNamaDokter.setText("Dr. " + namaDokter);
        lblSpesialisasi.setText(spesialisasi);

        // (Opsional) Simpan ID Dokter untuk query nanti
        // Buat variabel global dulu: private String loggedInDoctorId;
        // this.loggedInDoctorId = idDokter;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblNamaDokter = new javax.swing.JLabel();
        lblSpesialisasi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAntreanPasien = new javax.swing.JButton();
        btnRiwayatMedis = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Dokter - Klinik Sehat Selalu");

        panelSidebar.setBackground(new java.awt.Color(34, 40, 49));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 389));

        lblWelcome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(225, 225, 225));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Selamat Datang,");

        lblNamaDokter.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblNamaDokter.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaDokter.setText("dr. [Nama Dokter]");

        lblSpesialisasi.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblSpesialisasi.setForeground(new java.awt.Color(153, 153, 153));
        lblSpesialisasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpesialisasi.setText("[Spesialisasi Dokter]");

<<<<<<< HEAD
        btnAntreanPasien.setBackground(new java.awt.Color(255, 255, 255));
=======
>>>>>>> 8cae046 (final (kayaknya)2)
        btnAntreanPasien.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAntreanPasien.setForeground(java.awt.Color.white);
        btnAntreanPasien.setText("⏳️  Antrean Pasien Hari Ini");
        btnAntreanPasien.setBorderPainted(false);
        btnAntreanPasien.setContentAreaFilled(false);
        btnAntreanPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAntreanPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAntreanPasien.setIconTextGap(10);
        btnAntreanPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAntreanPasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAntreanPasienMouseExited(evt);
            }
        });
        btnAntreanPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntreanPasienActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        btnRiwayatMedis.setBackground(new java.awt.Color(255, 255, 255));
=======
>>>>>>> 8cae046 (final (kayaknya)2)
        btnRiwayatMedis.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRiwayatMedis.setForeground(java.awt.Color.white);
        btnRiwayatMedis.setText("📜  Riwayat Rekam Medis");
        btnRiwayatMedis.setBorderPainted(false);
        btnRiwayatMedis.setContentAreaFilled(false);
        btnRiwayatMedis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRiwayatMedis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRiwayatMedis.setIconTextGap(10);
        btnRiwayatMedis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRiwayatMedisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRiwayatMedisMouseExited(evt);
            }
        });
        btnRiwayatMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatMedisActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(220, 53, 69));
        btn_logout.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("[➜  Logout");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNamaDokter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSpesialisasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSidebarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_logout)
                        .addGap(0, 118, Short.MAX_VALUE))
<<<<<<< HEAD
                    .addComponent(btnAntreanPasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
                    .addComponent(btnAntreanPasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
>>>>>>> 8cae046 (final (kayaknya)2)
                    .addComponent(btnRiwayatMedis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNamaDokter)
                .addGap(12, 12, 12)
                .addComponent(lblSpesialisasi)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAntreanPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRiwayatMedis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                .addGap(475, 475, 475)
=======
                .addGap(463, 463, 463)
>>>>>>> 8cae046 (final (kayaknya)2)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSidebar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAntreanPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntreanPasienActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardAntrean"); // Panggil "cardAntrean"
    }//GEN-LAST:event_btnAntreanPasienActionPerformed

    private void btnRiwayatMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatMedisActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContent.getLayout();
        cl.show(panelContent, "cardRiwayat"); // Panggil "cardRiwayat"
    }//GEN-LAST:event_btnRiwayatMedisActionPerformed

    private void btnAntreanPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAntreanPasienMouseEntered
        // TODO add your handling code here:
        btnAntreanPasien.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnAntreanPasienMouseEntered

    private void btnAntreanPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAntreanPasienMouseExited
        // TODO add your handling code here:
        btnAntreanPasien.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnAntreanPasienMouseExited

    private void btnRiwayatMedisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayatMedisMouseEntered
        // TODO add your handling code here:
        btnRiwayatMedis.setForeground(new java.awt.Color(50,120,220));
    }//GEN-LAST:event_btnRiwayatMedisMouseEntered

    private void btnRiwayatMedisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayatMedisMouseExited
        // TODO add your handling code here:
        btnRiwayatMedis.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnRiwayatMedisMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (pilihan == JOptionPane.YES_OPTION) {
            new JFrame_Login().setVisible(true); // Buka login
            this.dispose(); // Tutup dashboard ini
        }
    }//GEN-LAST:event_btn_logoutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Main_Dokter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntreanPasien;
    private javax.swing.JButton btnRiwayatMedis;
    private javax.swing.JButton btn_logout;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNamaDokter;
    private javax.swing.JLabel lblSpesialisasi;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
