/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dokter;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import javax.swing.table.DefaultTableModel;
import Dokter.JDialog_Rekam_Medis;
import javax.swing.JOptionPane;
//import javax.swing.SwingUtilities;
//import java.awt.Frame;

/**
 *
 * @author USER
 */
public final class JPanel_Antrean_Pasien extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Manajemen_Pasien
     */
    
    private String loggedInDoctorId;
    
    public JPanel_Antrean_Pasien(String idDokter) {
        initComponents();
        this.loggedInDoctorId = idDokter;
        
        tblAntrean.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblAntrean.getTableHeader().setOpaque(false);
        tblAntrean.getTableHeader().setBackground(new java.awt.Color(32, 136, 203)); // Warna biru
        tblAntrean.getTableHeader().setForeground(new java.awt.Color(255,255,255)); // Teks putih
        
        tblAntrean.getColumnModel().getColumn(0).setMinWidth(0);
        tblAntrean.getColumnModel().getColumn(0).setMaxWidth(0);
        tblAntrean.getColumnModel().getColumn(0).setWidth(0);
        
        initPanel();
        
//        loadDataToTable(null);
    }
    
    private void initPanel() {
        // Set tanggal hari ini
        java.time.LocalDate today = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatter = 
            java.time.format.DateTimeFormatter.ofPattern("dd MMMM yyyy");
        lblTanggal.setText("Tanggal: " + today.format(formatter));

        // Muat data pertama kali
        loadDataAntrean();

        // Tambahkan Listener ke filter
        comboFilterStatus.addActionListener(e -> loadDataAntrean());

        // Tambahkan Listener ke Tabel (SANGAT PENTING)
        tblAntrean.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblAntrean.getSelectedRow() != -1) {
                // Cek status di kolom 4 (index 4)
                String status = tblAntrean.getValueAt(tblAntrean.getSelectedRow(), 4).toString();

                // Hanya aktifkan tombol jika statusnya "Menunggu"
                btnPeriksa.setEnabled(status.equals("Menunggu"));
            } else if (tblAntrean.getSelectedRow() == -1) {
                btnPeriksa.setEnabled(false); // Nonaktifkan jika tidak ada yg dipilih
            }
        });
    }
    
    public void loadDataAntrean() {
//        // 1. Dapatkan model tabel
//        DefaultTableModel model = (DefaultTableModel) tblAntrean.getModel();
//
//        // 2. Kosongkan tabel (hapus baris lama)
//        model.setRowCount(0);
//
//        // 3. Buat query SQL dasar
//        try {
//                String statusFilter = comboFilterStatus.getSelectedItem().toString();
//
//                // Query JOIN kunjungan dan pasien, filter berdasarkan DOKTER, TANGGAL, dan STATUS
//                String sql = "SELECT k.id_kunjungan, k.no_antrean, p.id_pasien, p.nama_pasien, k.status_kunjungan " +
//                             "FROM kunjungan k JOIN pasien p ON k.pasien_id = p.pasien_id " +
//                             "WHERE k.dokter_id = ? AND DATE(k.tanggal_kunjungan) = CURDATE() ";
//
//                if (!statusFilter.equals("Semua")) {
//                    sql += "AND k.status_kunjungan = '" + statusFilter + "' ";
//                }
//                sql += "ORDER BY k.no_antrean A                     SC";
//
//        // 5. Gunakan try-with-resources untuk koneksi
    //        try (Connection conn = Koneksi.getConnection(); // Asumsi Anda punya kelas Koneksi
    //             PreparedStatement pstmt = conn.prepareStatement(sql)) {
    //
    //            pstmt.setString(1, this.loggedInDoctorId);
    //
    //            // 7. Eksekusi query
    //            try (ResultSet rs = pstmt.executeQuery()) {
    //                // 8. Looping hasil dan tambahkan ke model tabel
    //                while (rs.next()) {
                    //    model.addRow(new Object[]{
                    //        rs.getString("id_kunjungan"),
                    //        rs.getString("no_antrean"),
                    //        rs.getString("id_pasien"),
                    //        rs.getString("nama_pasien"),
                    //        rs.getString("status_kunjungan")
                    //    });
                    // }
    //            }
    //
    //        } catch (Exception e) {
//                  JOptionPane.showMessageDialog(this, "Gagal memuat antrean: " + e.getMessage());
//              }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelFilter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboFilterStatus = new javax.swing.JComboBox<>();
        scrollPaneTabel = new javax.swing.JScrollPane();
        tblAntrean = new javax.swing.JTable();
        panelAksi = new javax.swing.JPanel();
        btnPeriksa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(51, 51, 51));
        lblJudul.setText("Antrean Pasien Hari Ini");

        lblTanggal.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(102, 102, 102));
        lblTanggal.setText("Tanggal: [placeholder]");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelFilter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tampilkan Status:");

        comboFilterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Selesai", "Semua" }));

        tblAntrean.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblAntrean.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"K001", "123", "P001", "Abc", "Menunggu"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Kunjungan", "No. Antrean", "ID Pasien", "Nama Pasien", "Status"
            }
        ));
        tblAntrean.setGridColor(new java.awt.Color(224, 224, 224));
        tblAntrean.setRowHeight(30);
        tblAntrean.setSelectionBackground(new java.awt.Color(50, 120, 220));
        tblAntrean.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblAntrean.setShowGrid(true);
        scrollPaneTabel.setViewportView(tblAntrean);

        panelAksi.setBackground(new java.awt.Color(255, 255, 255));

        btnPeriksa.setBackground(new java.awt.Color(50, 120, 220));
        btnPeriksa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPeriksa.setForeground(new java.awt.Color(255, 255, 255));
        btnPeriksa.setText("🔍  Periksa Pasien");
        btnPeriksa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriksaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAksiLayout = new javax.swing.GroupLayout(panelAksi);
        panelAksi.setLayout(panelAksiLayout);
        panelAksiLayout.setHorizontalGroup(
            panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPeriksa)
                .addContainerGap())
        );
        panelAksiLayout.setVerticalGroup(
            panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFilterLayout = new javax.swing.GroupLayout(panelFilter);
        panelFilter.setLayout(panelFilterLayout);
        panelFilterLayout.setHorizontalGroup(
            panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addGroup(panelFilterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFilterLayout.setVerticalGroup(
            panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblJudul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriksaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAntrean.getSelectedRow();

        // Pastikan ada baris terpilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pasien dari tabel terlebih dahulu.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil data penting dari tabel
        String idKunjungan = tblAntrean.getValueAt(selectedRow, 0).toString();
        String idPasien = tblAntrean.getValueAt(selectedRow, 2).toString();
        String namaPasien = tblAntrean.getValueAt(selectedRow, 3).toString();

        // Tampilkan JDialog Rekam Medis (yang akan kita buat selanjutnya)
        // Kita kirim data ini ke form rekam medis
        JDialog_Rekam_Medis formRekamMedis = new JDialog_Rekam_Medis(
            null, // Parent frame
            true, // Modal
            idKunjungan,
            idPasien,
            namaPasien
        );

        formRekamMedis.setVisible(true);

        // Setelah form ditutup (data disimpan/dibatalkan),
        // muat ulang data antrean
        loadDataAntrean();
        btnPeriksa.setEnabled(false); // Nonaktifkan kembali tombol
    }//GEN-LAST:event_btnPeriksaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeriksa;
    private javax.swing.JComboBox<String> comboFilterStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JPanel panelAksi;
    private javax.swing.JPanel panelFilter;
    private javax.swing.JScrollPane scrollPaneTabel;
    private javax.swing.JTable tblAntrean;
    // End of variables declaration//GEN-END:variables
}
